#!/bin/sh
curdir=`pwd`
version=$(cat conf-version)

if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi

if [ -d ../stage ] ; then
	/bin/rm -rf ../stage
fi
mkdir ../stage
cd ..
echo "Versioning procmail-$version"
cp -rp procmail-x stage/procmail-$version
cd stage/procmail-$version
echo "Cleaning procmail-$version"
make -s clean > /dev/null
make -s distclean > /dev/null
/bin/rm -rf autom4te.cache .deps
cd ..
echo "Archiving procmail-$version.tar.gz in `pwd`"
tar \
	--exclude="procmail-$version/.git" \
	--exclude="procmail-$version/debian"  \
	--exclude="procmail-$version/RCS" \
	-cf - procmail-"$version" \
	| gzip -c > $rpmbuild/SOURCES/procmail-"$version".tar.gz
echo "cp procmail-$version/procmail-rpmlintrc $rpmbuild/SOURCES"
cp procmail-$version/procmail-rpmlintrc $rpmbuild/SOURCES
dist=`uname -r |cut -d . -f4`
if [ $# -gt 0 ] ; then
	release=$1
else
	if [ -f /usr/bin/procmail ] ; then
		bdist=$(rpm -qf /usr/bin/procmail|cut -d- -f3|cut -d. -f3)
		if [ " $dist" = " $bdist" ] ; then
			bversion=$(rpm -qf /usr/bin/procmail|cut -d- -f2)
			if [ "$bversion" = "$version" ] ; then
				release=$(rpm -qf /usr/bin/procmail|cut -d- -f3|cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi
cd ..
echo "Clearing stage directory"
/bin/rm -rf stage
echo -n "Build RPM for procmail-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	tmprel=`cat procmail-x/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " 1.$release" ] ; then
		echo 1.$release > procmail-x/conf-release
		cd procmail-x
		make debian/Makefile
		make procmail.spec
		cp procmail.spec /tmp
		cd debian
		make
		cd ../..
	else
		make -s -C procmail-x procmail.spec
		cp procmail-x/procmail.spec /tmp
	fi
	rpmbuild -ba --clean /tmp/procmail.spec
	/bin/rm -f /tmp/procmail.spec
	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
	rpm --addsign $rpmbuild/RPMS/$build_arch/procmail-"$version"-"1.$release".$dist.$build_arch.rpm
	rpm --addsign $rpmbuild/SRPMS/procmail-"$version"-"1.$release".$dist.src.rpm
	echo -n "RPM lint for procmail-"$version"-1."$release" (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		(
		echo procmail
		rpmlint $rpmbuild/RPMS/$build_arch/procmail-"$version"-"1.$release".$dist.$build_arch.rpm
		echo ------------------------
		echo procmail-"$version"-"1.$release".$dist.src.rpm
		rpmlint $rpmbuild/SRPMS/procmail-"$version"-"1.$release".$dist.src.rpm
		echo ------------------------
		) 2>&1 | less
	fi
fi
echo -n "Remove Source (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	echo "/bin/rm -f $rpmbuild/SOURCES/procmail-$version.tar.bz2"
	/bin/rm -f $rpmbuild/SOURCES/procmail-$version.tar.bz2
	echo "/bin/rm -f $rpmbuild/SOURCES/procmail-rpmlintrc"
	/bin/rm -f $rpmbuild/SOURCES/procmail-rpmlintrc
fi
