#!/bin/sh
curdir=`pwd`
version=$(cat conf-version)

if [ -f /etc/debian_version ] ; then
	echo "you can't do rpmbuild on an insane system" 1>&2
	exit 1
fi

verbose=0
while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
	;;
    *) optarg=
	;;
    esac

    case "$1" in
    --release=*)
	release=$optarg
    ;;
    --verbose)
	verbose=1
    ;;
    *)
    echo "invalid option [$1]"
    read key
    usage 1
    ;;
    esac

    shift
done

if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi
copy_src=0
echo -n "Copy Source Files - "
read key
if [ " $key" = " y" -o " $key" = " Y" ] ; then
	copy_src=1
fi

make -s logalert.spec
if [ $? -ne 0 ] ; then
	echo "make failed" 1>&2
	exit 0
fi
if [ $copy_src -eq 1 ] ; then
	if [ -d ../stage ] ; then
		/bin/rm -rf ../stage
	fi
	mkdir ../stage
	cd ..
	echo "Versioning logalert-$version"
	cp -rp logalert-x stage/logalert-$version
	cd stage/logalert-$version
	echo "Cleaning logalert-$version"
	make -s clean > /dev/null
	make -s distclean > /dev/null
	/bin/rm -rf autom4te.cache .deps
	cd ..
	echo "Archiving logalert-$version.tar.gz in `pwd`"
	tar \
		--exclude="logalert-$version/.git" \
		--exclude="logalert-$version/debian"  \
		--exclude="logalert-$version/RCS" \
		-cf - logalert-"$version" \
		| gzip -c > $rpmbuild/SOURCES/logalert-"$version".tar.gz
	echo "cp logalert-$version/logalert-rpmlintrc $rpmbuild/SOURCES"
	cp logalert-$version/logalert-rpmlintrc $rpmbuild/SOURCES
	cd ..
	echo "Clearing stage directory"
	/bin/rm -rf stage
else
	cd ..
fi
dist=`uname -r |cut -d . -f4`
if [ -z "$release" ] ; then
	if [ -f /usr/bin/logalert ] ; then
		bdist=$(rpm -qf /usr/bin/logalert|cut -d- -f3|cut -d. -f3)
		if [ " $dist" = " $bdist" ] ; then
			bversion=$(rpm -qf /usr/bin/logalert|cut -d- -f2)
			if [ "$bversion" = "$version" ] ; then
				release=$(rpm -qf /usr/bin/logalert|cut -d- -f3|cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi
echo -n "Build RPM for logalert-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	tmprel=`cat logalert-x/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " 1.$release" ] ; then
		echo 1.$release > logalert-x/conf-release
		cd logalert-x
		make debian/Makefile
		make logalert.spec
		cp logalert.spec /tmp
		cd debian
		make
		cd ../..
	else
		make -s -C logalert-x logalert.spec
		cp logalert-x/logalert.spec /tmp
	fi
	if [ $verbose -eq 0 ] ; then
		echo "rpmbuild -ba --clean --quiet /tmp/logalert.spec"
		rpmbuild -ba --clean --quiet /tmp/logalert.spec
	else
		echo "rpmbuild -ba --clean /tmp/logalert.spec"
		rpmbuild -ba --clean /tmp/logalert.spec
	fi
	if [ $? -eq 0 ] ; then
		/bin/rm -f /tmp/logalert.spec
		build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
		rpm --addsign $rpmbuild/RPMS/$build_arch/logalert-"$version"-"1.$release".$dist.$build_arch.rpm
		rpm --addsign $rpmbuild/SRPMS/logalert-"$version"-"1.$release".$dist.src.rpm
		echo -n "RPM lint for logalert-"$version"-1."$release" (Y/N) - "
		read key
		if [ " $key" = " Y" -o " $key" = " y" ] ; then
			(
			echo logalert
			rpmlint $rpmbuild/RPMS/$build_arch/logalert-"$version"-"1.$release".$dist.$build_arch.rpm
			echo ------------------------
			echo logalert-"$version"-"1.$release".$dist.src.rpm
			rpmlint $rpmbuild/SRPMS/logalert-"$version"-"1.$release".$dist.src.rpm
			echo ------------------------
			) 2>&1 | less
		fi
	else
		/bin/rm -f /tmp/logalert.spec
	fi
fi
if [ $copy_src -eq 1 ] ; then
	echo -n "Remove Source (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		echo "/bin/rm -f $rpmbuild/SOURCES/logalert-$version.tar.bz2"
		/bin/rm -f $rpmbuild/SOURCES/logalert-$version.tar.bz2
		echo "/bin/rm -f $rpmbuild/SOURCES/logalert-rpmlintrc"
		/bin/rm -f $rpmbuild/SOURCES/logalert-rpmlintrc
	fi
fi
