#!/bin/sh
#
# This script prepares artifacts that can be downloaded for openSUSE build service
# It creates name.tar.gz, debian.tar.gz and name.spec
#
set -e

prepare_artifacts()
{
  pkg_dir=$1
  stage=$2

  skip_dsc_spec=$3

  real_name=$(basename $pkg_dir)
  echo $pkg_dir|grep "/" >/dev/null
  if [ $? -eq 0 ] ; then
    pkg_name=$(basename $pkg_dir|sed -e 's{-x{{g')
  else
    pkg_name=$(echo $pkg_dir|sed -e 's{-x{{g')
  fi
  if [ -d $pkg_dir ] ; then
    cd $pkg_dir
  else
    echo "$pkg_dir: No such file or directory" 1>&2
    return 1
  fi
  ver=$(cat conf-version)
  echo Preparing $pkg_name-$ver
  if [ -z "$ver" ] ; then
    echo "no version found for package $pkg_name" 1>&2
    exit 1
  fi
  if [ -f default.configure -a ! -f ./configure -o ! -f ./Makefile ] ; then
    ./default.configure
  fi

  mkdir -p $stage
  if [ $skip_dsc_spec -eq 0 ] ; then
    # Create spec file
    if [ -f $pkg_name.spec.in -a -f Makefile -a ! -f ./$pkg_name.spec ] ; then
      make $pkg_name.spec
    fi
    if [ -f $pkg_name.spec ] ; then
      cp $pkg_name.spec $stage
    fi
  
    if [ -d debian ] ; then
      # Create debian.tar.gz
      if [ -f debian/Makefile.in ] ; then
        make debian/Makefile
      fi
      # all indimail, indimail-mta packages have debian/Makefile
      if [ -f debian/Makefile ] ; then
        make -C debian
        cp debian/debian.tar.gz $stage
        cp debian/*.dsc $stage
        make -C debian clean >/dev/null
      fi
      #remove debian directory
      /bin/rm -rf $pkg_name-$ver/debian
    fi
    if [ -f $pkg_name-rpmlintrc ] ; then
      cp $pkg_name-rpmlintrc $stage
    fi
  fi

  if [ -f Makefile ] ; then
    make clean >/dev/null
  fi

  cp -rpf . $stage/$pkg_name-$ver
  # change cwd to staging directory
  cd $stage
  ln -s $pkg_name-$ver $real_name

  tar cfz $pkg_name-$ver.tar.gz $pkg_name-$ver
  if [ $skip_dsc_spec -eq 0 ] ; then
    /bin/rm -rf $pkg_name-$ver
  fi
}

if [ $# -ne 1 ] ; then
  echo "USAGE: prepare_obs name" 1>&2
  exit 1
fi
name=$1
SAVE=$PWD
if [ -f $name.packages ] ; then
  /bin/rm -rf $HOME/stage/$name-$ver
  for i in `cat $name.packages`
  do
    prepare_artifacts $i $HOME/stage 1
    cd $SAVE
  done
  if [ ! -f conf-version ] ; then
    echo "$name: conf-version: No such file or directory" 1>&2
    return 1
  fi
  cd $SAVE
  ver=$(cat conf-version)
  mkdir -p $HOME/stage
  echo "Preparing $name-$ver"
  cp -rp . $HOME/stage/$name-$ver
  cd $HOME/stage/$name-$ver
  if [ -f Makefile ] ; then
    make $name.spec $name-rpmlintrc
    cp $name.spec $name-rpmlintrc $HOME/stage
  fi
  if [ -f debian/Makefile.in ] ; then
    make debian/Makefile
  fi
  if [ -f debian/Makefile ] ; then
    make -C debian
    cp debian/debian.tar.gz $HOME/stage
    cp debian/*.dsc $HOME/stage
    make -C debian clean >/dev/null
  fi
  cd $SAVE
  /bin/rm -rf $HOME/stage/$name-$ver
  for pkg_dir in `cat $name.packages`
  do
    real_name=$(basename $pkg_dir)
    pkg_name=$(echo $real_name|sed -e 's{-x{{g')
    if [ ! -f $pkg_dir/conf-version ] ; then
      echo "$pkg_dir/conf-version: No such file or directory" 1>&2
      return 1
    fi
    ver=$(cat $pkg_dir/conf-version)
    /bin/rm -rf $HOME/stage/$pkg_name-$ver
	/bin/rm -f $HOME/stage/$real_name
  done
else
  prepare_artifacts $1 $HOME/stage 0
fi
ls -l $HOME/stage
##############
#mv $HOME/stage/* $HOME
rmdir $HOME/stage --ignore-fail-on-non-empty
##############
echo HOME=$HOME
exit $?
