#!/bin/sh
#
# utility to append changelog to indimail.spec
#
flag=0
if [ $# -eq 1 ] ; then
	file=$1
else
	file=doc/ChangeLog
fi
cat $file|while read line
do
	echo "$line"|grep "^*" > /dev/null
	if [ $? -eq 0 -a $flag -ne 0 ] ; then
		break
	fi
	echo "$line" | grep "^[0-9]*/.*/.*" > /dev/null # skip dates
	if [ $? -eq 0 ] ; then
		continue
	fi
	if [ $flag -eq 0 ] ; then # first line
		echo "* `date +"%a %b %d %Y %H:%M:%S %z"` indimail-auth@indimail.org" @version@-@release@%{?dist}
		flag=1
		continue
	elif [ $flag -eq 1 ] ; then
		echo "$line"
		flag=2
		continue
	fi
	echo "$line" |grep "^[0-9]" > /dev/null
	if [ $? -eq 0 ] ; then
		echo "$line"
	elif [ -n "$line" ] ; then
		echo "    $line"
	fi
done

