#!/bin/sh
version=$(head -1 conf-version)
courier_version=$(cat ../courier-imap-x/conf-version)
fetchmail_version=$(cat ../fetchmail-x/conf-version)

get_tar_files()
{
(
for i in `grep "^Source" indimail-access/indimail-access.spec | awk '{print $2}' | grep "\.tar"`
do
	i=`basename $i`
	echo $i
done
) | sort -u | sed \
	-e 's/%{name}/indimail/g' \
	-e "s/%{version}/$version/g" \
	-e "s/%{courier_version}/$courier_version/g" \
	-e "s/%{fetchmail_version}/$fetchmail_version/g"
}

get_non_tar_files()
{
(
for i in `grep "^Source" $1 | grep -v "\.tar" | awk '{print $2}'`
do
	i=`basename $i`
	echo $i
done
) | sort -u | sed \
	-e 's/%{name}/indimail/g' \
	-e "s/%{version}/$version/g" \
	-e "s/%{courier_version}/$courier_version/g" \
	-e "s/%{fetchmail_version}/$fetchmail_version/g"
}

get_dirname()
{
	echo $1 | sed \
		-e 's}.tar.gz}}g' \
		-e 's}.tar.bz2}}g' \
		-e 's}.tar.xz}}g'
}

if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi

make -s indimail-access.spec
if [ $? -ne 0 ] ; then
	echo "make failed" 1>&2
	exit 0
fi
if [ -d ../stage ] ; then
	/bin/rm -rf ../stage
fi
mkdir ../stage
cd ..
list=`get_tar_files`
for i in $list
do
	echo "Versioning $i"
	dir=`echo $i | sed -e 's{-[0-9].*tar.bz2{{g' -e 's{-[0-9].*tar.xz{{g'`
	if [ ! -d $dir-x ] ; then
		echo "$dir-x: No such file or directory" 1>&2
		exit 1
	fi
	case "$dir" in
		courier-imap)
		package_version=$courier_version
		;;
		fetchmail)
		package_version=$fetchmail_version
		;;
	esac
	/bin/cp -rp "$dir"-x stage/$dir-"$package_version"
	cd stage/$dir-"$package_version"
	echo "Cleaning $dir-$package_version"
	make -s clean > /dev/null
	make -s distclean > /dev/null
	/bin/rm -rf autom4te.cache .deps
	cd ..
	do_archive="gz"
	case "$do_archive" in
		gz)
		echo "Archiving $dir-$package_version.tar.gz in `pwd`"
		tar \
		--exclude="$dir/.git" \
		--exclude="$dir/debian"  \
		--exclude="$dir/RCS" \
		-cf - $dir-$package_version \
		| gzip -c > $rpmbuild/SOURCES/"$dir"-"$package_version".tar.gz
		SRC="$rpmbuild/SOURCES/"$dir"-"$package_version".tar.gz $SRC"
		;;
	esac
	cd ..
done
echo "Copying permissions files and rpmlintrc"
for i in `get_non_tar_files indimail-access/indimail-access.spec`
do
	echo "/bin/cp -p indimail-access/$i $rpmbuild/SOURCES"
	/bin/cp -p indimail-access/$i $rpmbuild/SOURCES
	SRC="$rpmbuild/SOURCES/$i $SRC"
done
echo "Preparing indimail-access-"$version""
dist=`uname -r |cut -d . -f4`
if [ $# -gt 0 ] ; then
	release=$1
else
	if [ -f /usr/bin/altermime ] ; then
		idist=$(rpm -qf /usr/bin/altermime|cut -d- -f4|cut -d. -f3)
		if [ " $dist" = " $idist" ] ; then
			iversion=$(rpm -qf /usr/bin/altermime|cut -d- -f3)
			if [ "$iversion" = "$version" ] ; then
				release=$(rpm -qf /usr/bin/altermime | cut -d- -f4 | cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi
echo "Clearing stage directory"
/bin/rm -rf stage
echo -n "Build RPM for indimail-access-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	tmprel=`cat indimail-access/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " 1.$release" ] ; then
		echo 1.$release > indimail-access/conf-release
		cd indimail-access
		make indimail-access.spec
		cp indimail-access.spec /tmp
		cd debian
		make
		cd ../..
	else
		cp indimail-access/indimail-access.spec /tmp
	fi
	rpmbuild -ba --clean /tmp/indimail-access.spec
	/bin/rm -f /tmp/indimail.spec
	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
	rpm --addsign $rpmbuild/RPMS/$build_arch/indimail-access-"$version"-"1.$release".$dist.$build_arch.rpm
	rpm --addsign $rpmbuild/SRPMS/indimail-access-"$version"-"1.$release".$dist.src.rpm
	echo -n "RPM lint for indimail-access-"$version"-1."$release" (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		(
		echo indimail-access
		rpmlint $rpmbuild/RPMS/$build_arch/indimail-access-"$version"-"1.$release".$dist.$build_arch.rpm
		echo ------------------------
		echo indimail-access-"$version"-"1.$release".$dist.src.rpm
		rpmlint $rpmbuild/SRPMS/indimail-access-"$version"-"1.$release".$dist.src.rpm
		echo ------------------------
		) 2>&1 | less
	fi
fi
echo -n "Remove Source (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	for i in $SRC
	do
		echo "/bin/rm -f $i"
		/bin/rm -f $i
	done
fi
