#!/bin/sh
if [ ! -f /etc/debian_version ] ; then
	echo "Not a debian or ubuntu distribution" 1>&2
	exit 1
fi
courier_version=$(cat ../courier-imap-x/conf-version)
fetchmail_version=$(cat ../fetchmail-x/conf-version)

make -s debian/Makefile
make -s -C debian
rm -rf                   $HOME/stage/indimail-access
mkdir -p                 $HOME/stage/indimail-access
cp -rp ../courier-imap-x $HOME/stage/indimail-access/courier-imap-$courier_version
cp -rp ../fetchmail-x    $HOME/stage/indimail-access/fetchmail-$fetchmail_version
cp -rp debian            $HOME/stage/indimail-access
cd                       $HOME/stage/indimail-access
dpkg-buildpackage -tc -b -d
rm -rf                   $HOME/stage/indimail-access
ls -lt $HOME/stage
