#!/bin/sh
set -x
rcsflag=0
make clean
make distclean
/bin/rm -r autom4te.cache
ver=2.0
if [ -d RCS ] ; then
	rcsflag=1
	mv RCS ../RCSiwebadmin
fi
cd ..
if [ -f $HOME/.rpmmacros ] ; then
	topdir=`grep ^%_topdir $HOME/.rpmmacros|awk '{print $2}'`
else
	topdir=$HOME/rpmbuild
fi
tar cf - iwebadmin-$ver | gzip -c > $topdir/SOURCES/iwebadmin-$ver.tar.gz
cp iwebadmin-$ver/iwebadmin-$ver-rpmlintrc $topdir/SOURCES
cd iwebadmin-$ver
if [ $rcsflag -eq 1 ] ; then
	mv ../RCSiwebadmin ./RCS
fi
rpmbuild -ba --clean iwebadmin.spec
