#!/bin/sh
altermime_version=$(cat ../altermime-x/conf-version)
ripmime_version=$(cat ../ripmime-x/conf-version)
fortune_version=$(cat ../fortune-x/conf-version)
mpack_version=$(cat ../mpack-x/conf-version)
flash_version=$(cat ../flash-x/conf-version)

if [ -d ../stage ] ; then
	/bin/rm -rf ../stage
fi
mkdir -p ../stage
cp -rp ../altermime-x ../stage/altermime-$altermime_version
cp -rp ../ripmime-x   ../stage/ripmime-$ripmime_version
cp -rp ../fortune-x   ../stage/fortune-$fortune_version
cp -rp ../flash-x     ../stage/flash-$flash_version
cp -rp ../mpack-x     ../stage/mpack-$mpack_version
make -s
make -s -C debian
cp -rp debian ../stage
cd ../stage
for i in alterime-$altermime_version ripmime-$ripmime_version \
	fortune-$fortune_version flash-$flash_version mpack-$mpack_version
do
	make -s -C $i clean || true
	make -s -C $i distclean || true
done
dpkg-buildpackage -tc -b
cd ..
/bin/rm -r stage
