#!/bin/sh
# $Log: catChangeLog,v $
# Revision 1.3  2020-05-24 12:02:18+05:30  Cprogrammer
# fixed release number
#
# Revision 1.2  2020-05-21 14:38:34+05:30  Cprogrammer
# fixed timestamp
#
# Revision 1.1  2019-05-29 00:47:06+05:30  Cprogrammer
# Initial revision
#
# utility to append changelog to indimail.spec
#
#
# $Id: catChangeLog,v 1.3 2020-05-24 12:02:18+05:30 Cprogrammer Exp mbhangui $
#
flag=0
if [ $# -eq 1 ] ; then
	file=$1
else
	file=doc/ChangeLog.indimail
fi
cat $file|while read line
do
	echo "$line"|grep "^*" > /dev/null
	if [ $? -eq 0 -a $flag -ne 0 ] ; then
		break
	fi
	echo "$line" | grep "^[0-9]*/.*/.*" > /dev/null # skip dates
	if [ $? -eq 0 ] ; then
		continue
	fi
	if [ $flag -eq 0 ] ; then # first line
		echo "* `date +"%a %b %d %Y %H:%M:%S %z"` indimail-virtualdomains@indimail.org" @version@-@release@%{?dist}
		flag=1
		continue
	elif [ $flag -eq 1 ] ; then
		echo "$line"
		flag=2
		continue
	fi
	echo "$line" |grep "^[0-9]" > /dev/null
	if [ $? -eq 0 ] ; then
		echo "$line"
	else
		echo "    $line"
	fi
done

