#!/bin/sh
#
# $Log: cputime,v $
# Revision 1.1  2019-05-29 01:00:16+05:30  Cprogrammer
# Initial revision
#
# cputime
#
# $Id: cputime,v 1.1 2019-05-29 01:00:16+05:30 Cprogrammer Exp mbhangui $
#
if [ $# -ne 1 ] ; then
	echo "USAGE: cputime time_in_min"
	exit 1
fi
MAX=$1
/bin/ps -ef| /bin/awk -v MAX=$MAX '{
	user=$1
	pid=$2
	cputime=$7
	process=$8
	if(cputime != "TIME")
	{
		n = split(cputime, abc, '/:/');
		total = abc[1] * 3600 + abc[2] * 60 + abc[3];
		if(total > MAX)
			printf("%-30s %-8s %5d %s\n", process, user, pid, cputime);
	}
}'
