#!/bin/sh
version=$(head -1 conf-version)
courier_version=$(grep courier_version indimail.spec.in | head -1| awk '{print $3}')
bogofilter_version=$(grep bogofilter_version indimail.spec.in | head -1| awk '{print $3}')
pam_multi_version=$(grep pam_multi_version indimail.spec.in | head -1| awk '{print $3}')
fetchmail_version=$(grep fetchmail_version indimail.spec.in | head -1| awk '{print $3}')
fortune_version=$(grep fortune_version indimail.spec.in | head -1| awk '{print $3}')
nssd_version=$(grep nssd_version indimail.spec.in | head -1| awk '{print $3}')
flash_version=$(grep flash_version indimail.spec.in | head -1| awk '{print $3}')

get_tar_files()
{
(
for i in `grep "^Source" indimail-x/indimail.spec.in | grep -v Source0 | awk '{print $2}' | grep "\.tar"`
do
	i=`basename $i`
	echo $i
done
) | sort -u | sed \
	-e 's/%{name}/indimail/g' \
	-e "s/%{version}/$version/g" \
	-e "s/%{courier_version}/$courier_version/g" \
	-e "s/%{flash_version}/$flash_version/g" \
	-e "s/%{bogofilter_version}/$bogofilter_version/g" \
	-e "s/%{fetchmail_version}/$fetchmail_version/g" \
	-e "s/%{pam_multi_version}/$pam_multi_version/g" \
	-e "s/%{fortune_version}/$fortune_version/g" \
	-e "s/%{nssd_version}/$nssd_version/g"
}

get_non_tar_files()
{
(
for i in `grep "^Source" $1 | grep -v "\.tar" | awk '{print $2}'`
do
	i=`basename $i`
	echo $i
done
) | sort -u | sed \
	-e 's/%{name}/indimail/g' \
	-e "s/%{version}/$version/g" \
	-e "s/%{courier_version}/$courier_version/g" \
	-e "s/%{flash_version}/$flash_version/g" \
	-e "s/%{bogofilter_version}/$bogofilter_version/g" \
	-e "s/%{fetchmail_version}/$fetchmail_version/g" \
	-e "s/%{pam_multi_version}/$pam_multi_version/g" \
	-e "s/%{fortune_version}/$fortune_version/g" \
	-e "s/%{nssd_version}/$nssd_version/g"
}

get_dirname()
{
	echo $1 | sed \
		-e 's}.tar.gz}}g' \
		-e 's}.tar.bz2}}g' \
		-e 's}.tar.xz}}g'
}

if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi

mkdir ../stage
cd ..
list=`get_tar_files`
for i in $list
do
	echo $i | grep courier-imap > /dev/null
	if [ $? -eq 0 ] ; then
		if [ ! -d courier-imap-x ] ; then
			echo "$i: No such file or directory" 1>&2
			exit 1
		fi
		echo "Preparing courier-imap-"$courier_version""
		/bin/cp -rp courier-imap-x stage/courier-imap-"$courier_version"
		cd stage/courier-imap-"$courier_version"
		make -s clean > /dev/null
		make -s distclean > /dev/null
		/bin/rm -rf autom4te.cache .deps
		cd ..
		tar cf - courier-imap-"$courier_version" | \
			bzip2 -c > $rpmbuild/SOURCES/courier-imap-"$courier_version".tar.bz2
		SRC="$rpmbuild/SOURCES/courier-imap-"$courier_version".tar.bz2 $SRC"
		cd ..
		continue
	fi
	do_archive="gz"
	echo $i | grep bogofilter > /dev/null
	if [ $? -eq 0 ] ; then
		do_archive="bz2"
	fi
	echo $i | grep fetchmail > /dev/null
	if [ $? -eq 0 ] ; then
		do_archive="xz"
	fi
	dir=`get_dirname $i`
	if [ ! -d $dir ] ; then
		echo "$dir: No such file or directory" 1>&2
		exit 1
	fi
	case "$dir" in
		"bogofilter-$bogofilter_version"|"fetchmail-$fetchmail_version"|"nssd-$nssd_version")
		echo "Preparing $dir"
		/bin/cp -rp $dir stage
		cd stage/$dir
		echo "Cleaning $dir"
		make -s clean > /dev/null
		make -s distclean > /dev/null
		/bin/rm -rf autom4te.cache .deps
		cd ..
		case "$do_archive" in
			gz)
				tar \
				--exclude="$dir/.git" \
				--exclude="$dir/debian"  \
				--exclude="$dir/RCS" \
				-cf - $dir \
				| gzip -c > $rpmbuild/SOURCES/$dir.tar.gz
				SRC="$rpmbuild/SOURCES/$dir.tar.gz $SRC"
				;;
			bz2)
				tar \
				--exclude="$dir/.git" \
				--exclude="$dir/debian"  \
				--exclude="$dir/RCS" \
				-cf - $dir \
				| bzip2 -c > $rpmbuild/SOURCES/$dir.tar.bz2
				SRC="$rpmbuild/SOURCES/$dir.tar.bz2 $SRC"
				;;
			xz)
				tar \
				--exclude="$dir/.git" \
				--exclude="$dir/debian"  \
				--exclude="$dir/RCS" \
				-cf - $dir \
				| xz -c > $rpmbuild/SOURCES/$dir.tar.xz
				SRC="$rpmbuild/SOURCES/$dir.tar.xz $SRC"
				;;
		esac
		cd ..
		;;
		*)
		/bin/cp -rp $dir stage
		;;
	esac
done
echo "Preparing indimail-"$version""
/bin/cp -rp indimail-x stage/indimail-"$version"
cd stage/indimail-"$version"
make clean > /dev/null
make distclean > /dev/null
/bin/rm -rf autom4te.cache .deps
/bin/rm -rf eps-1.2/autom4te.cache eps-1.2/.deps
cd ..
tar \
	--exclude="indimail-$version/.git" \
	--exclude="indimail-$version/debian"  \
	--exclude="indimail-$version/RCS" \
	-cf - indimail-"$version" \
	| gzip -c > $rpmbuild/SOURCES/indimail-"$version".tar.gz
SRC="$rpmbuild/SOURCES/indimail-"$version".tar.gz $SRC"

echo "Copying permissions files and rpmlintrc"
for i in `get_non_tar_files ../indimail-x/indimail.spec.in`
do
	/bin/cp -p indimail-"$version"/$i $rpmbuild/SOURCES
	SRC="$rpmbuild/SOURCES/$i $SRC"
done
# copy rest of source
for i in $list
do
	echo $i | grep courier-imap > /dev/null
	if [ $? -eq 0 ] ; then
		continue
	fi
	do_archive="gz"
	echo $i | grep bogofilter > /dev/null
	if [ $? -eq 0 ] ; then
		do_archive="bz2"
	fi
	echo $i | grep fetchmail > /dev/null
	if [ $? -eq 0 ] ; then
		do_archive="xz"
	fi
	dir=`get_dirname $i`
	if [ ! -d $dir ] ; then
		echo "$dir: No such file or directory" 1>&2
		exit 1
	fi
	case "$dir" in
		"bogofilter-$bogofilter_version"|"fetchmail-$fetchmail_version"|"nssd-$nssd_version")
		;;
		*)
		echo "Preparing $dir"
		/bin/rm -rf $dir/autom4te.cache $dir/.deps
		case "$do_archive" in
			gz)
				tar \
				--exclude="$dir/.git" \
				--exclude="$dir/debian"  \
				--exclude="$dir/RCS" \
				-cf - $dir \
				| gzip -c > $rpmbuild/SOURCES/$dir.tar.gz
				SRC="$rpmbuild/SOURCES/$dir.tar.gz $SRC"
				;;
			bz2)
				tar \
				--exclude="$dir/.git" \
				--exclude="$dir/debian"  \
				--exclude="$dir/RCS" \
				-cf - $dir \
				| bzip2 -c > $rpmbuild/SOURCES/$dir.tar.bz2
				SRC="$rpmbuild/SOURCES/$dir.tar.bz2 $SRC"
				;;
			xz)
				tar \
				--exclude="$dir/.git" \
				--exclude="$dir/debian"  \
				--exclude="$dir/RCS" \
				-cf - $dir \
				| xz -c > $rpmbuild/SOURCES/$dir.tar.xz
				SRC="$rpmbuild/SOURCES/$dir.tar.xz $SRC"
				;;
		esac
		;;
	esac
done

dist=`uname -r |cut -d . -f4`
if [ $# -gt 0 ] ; then
	release=$1
else
	if [ -f /usr/bin/vuserinfo ] ; then
		idist=$(rpm -qf /usr/bin/vuserinfo|cut -d- -f3|cut -d. -f3)
		if [ " $dist" = " $idist" ] ; then
			iversion=$(rpm -qf /usr/bin/vuserinfo|cut -d- -f2)
			if [ "$iversion" = "$version" ] ; then
				release=$(rpm -qf /usr/bin/vuserinfo | cut -d- -f3 | cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi
cd ..
echo "Clearing stage directory"
/bin/rm -rf stage
echo -n "Build RPM for indimail-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	tmprel=`cat indimail-x/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " 1.$release" ] ; then
		echo 1.$release > indimail-x/conf-release
		cd indimail-x
		make indimail.spec
		cp indimail.spec /tmp
		cd debian
		make
		cd ../..
	else
		cp indimail-x/indimail.spec /tmp
	fi
	rpmbuild -ba --clean /tmp/indimail.spec
	/bin/rm -f /tmp/indimail.spec
	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
	for i in indimail indimail-devel libindimail
	do
		rpm --addsign $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
	done
	rpm --addsign $rpmbuild/SRPMS/indimail-"$version"-"1.$release".$dist.src.rpm
	echo -n "RPM lint for indimail-"$version"-1."$release" (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		(
		for i in indimail indimail-devel libindimail
		do
			echo $i
			rpmlint $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
			echo ------------------------
		done
		echo indimail-"$version"-"1.$release".$dist.src.rpm
		rpmlint $rpmbuild/SRPMS/indimail-"$version"-"1.$release".$dist.src.rpm
		echo ------------------------
		) 2>&1 | less
	fi
fi
echo -n "Remove Source (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	for i in $SRC
	do
		echo "/bin/rm -f $i"
		/bin/rm -f $i
	done
fi
