#!/bin/sh
if [ ! -f /etc/debian_version ] ; then
	echo "Not a debian or ubuntu distribution" 1>&2
	exit 1
fi
indimail_version=$(cat conf-version)

echo "Cleaning Stage"
/bin/rm -rf $HOME/stage/indimail-$indimail_version
echo "Copying Stage"
mkdir -p    $HOME/stage/indimail-$indimail_version
cp -rp .    $HOME/stage/indimail-$indimail_version
cd          $HOME/stage/indimail-$indimail_version
make -s debian/Makefile
make -s -C debian
dpkg-buildpackage -tc -b
if [ $? -eq 0 ] ; then
	/bin/rm -rf $HOME/stage/indimail-$indimail_version
	ls -lt $HOME/stage
fi
