#!/bin/sh
version=$(head -1 conf-version)
courier_version=$(grep courier_version indimail.spec.in | head -1| awk '{print $3}')
bogofilter_version=$(grep bogofilter_version indimail.spec.in | head -1| awk '{print $3}')
pam_multi_version=$(grep pam_multi_version indimail.spec.in | head -1| awk '{print $3}')
fetchmail_version=$(grep fetchmail_version indimail.spec.in | head -1| awk '{print $3}')
nssd_version=$(grep nssd_version indimail.spec.in | head -1| awk '{print $3}')
nonssd=1
nopam_multi=1

get_tar_files()
{
(
PATT="Source0"
if [ $nonssd -eq 1 ] ; then
	PATT="$PATT|nssd"
fi
if [ $nopam_multi -eq 1 ] ; then
	PATT="$PATT|pam-multi"
fi
for i in `grep "^Source" indimail-x/indimail.spec.in | egrep -v $PATT | awk '{print $2}' | grep "\.tar"`
do
	i=`basename $i`
	echo $i
done
) | sort -u | sed \
	-e 's/%{name}/indimail/g' \
	-e "s/%{version}/$version/g" \
	-e "s/%{courier_version}/$courier_version/g" \
	-e "s/%{bogofilter_version}/$bogofilter_version/g" \
	-e "s/%{fetchmail_version}/$fetchmail_version/g" \
	-e "s/%{pam_multi_version}/$pam_multi_version/g" \
	-e "s/%{nssd_version}/$nssd_version/g"
}

get_non_tar_files()
{
(
for i in `grep "^Source" $1 | grep -v "\.tar" | awk '{print $2}'`
do
	i=`basename $i`
	echo $i
done
) | sort -u | sed \
	-e 's/%{name}/indimail/g' \
	-e "s/%{version}/$version/g" \
	-e "s/%{courier_version}/$courier_version/g" \
	-e "s/%{bogofilter_version}/$bogofilter_version/g" \
	-e "s/%{fetchmail_version}/$fetchmail_version/g" \
	-e "s/%{pam_multi_version}/$pam_multi_version/g" \
	-e "s/%{nssd_version}/$nssd_version/g"
}

get_dirname()
{
	echo $1 | sed \
		-e 's}.tar.gz}}g' \
		-e 's}.tar.bz2}}g' \
		-e 's}.tar.xz}}g'
}

if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi

make -s indimail.spec
if [ $? -ne 0 ] ; then
	echo "make failed" 1>&2
	exit 0
fi
if [ -d ../stage ] ; then
	/bin/rm -rf ../stage
fi
mkdir ../stage
cd ..
list=`get_tar_files`
for i in $list
do
	case "$i" in
		courier-imap-"$courier_version".tar.bz2)
		if [ ! -d courier-imap-x ] ; then
			echo "$i: No such file or directory" 1>&2
			exit 1
		fi
		echo "Versioning courier-imap-"$courier_version".tar.bz2"
		/bin/cp -rp courier-imap-x stage/courier-imap-"$courier_version"
		cd stage/courier-imap-"$courier_version"
		echo "Cleaning courier-imap-$courier_version"
		make -s clean > /dev/null
		make -s distclean > /dev/null
		/bin/rm -rf autom4te.cache .deps
		cd ../..
		;;
		nssd-"$nssd_version".tar.gz)
		if [ ! -d nssd-x ] ; then
			echo "$i: No such file or directory" 1>&2
			exit 1
		fi
		echo "Versioning nssd-"$nssd_version".tar.gz"
		/bin/cp -rp nssd-x stage/nssd-"$nssd_version"
		cd stage/nssd-"$nssd_version"
		echo "Cleaning nssd-$nssd_version"
		make -s clean > /dev/null
		make -s distclean > /dev/null
		/bin/rm -rf autom4te.cache .deps
		cd ../..
		;;
		pam-multi-"$pam_multi_version".tar.gz)
		if [ ! -d pam-multi-x ] ; then
			echo "$i: No such file or directory" 1>&2
			exit 1
		fi
		echo "Versioning pam-multi-"$pam_multi_version".tar.gz"
		/bin/cp -rp pam-multi-x stage/pam-multi-"$pam_multi_version"
		cd stage/pam-multi-"$pam_multi_version"
		echo "Cleaning pam-multi-$pam_multi_version"
		make -s clean > /dev/null
		make -s distclean > /dev/null
		/bin/rm -rf autom4te.cache .deps
		cd ../..
		;;
	esac
	do_archive="gz"
	echo $i | egrep "bogofilter|courier" > /dev/null
	if [ $? -eq 0 ] ; then
		do_archive="bz2"
	fi
	echo $i | grep fetchmail > /dev/null
	if [ $? -eq 0 ] ; then
		do_archive="xz"
	fi
	dir=`get_dirname $i`
	case "$dir" in
		nssd-$nssd_version|courier-imap-$courier_version|pam-multi-$pam_multi_version)
		;;
		*)
		if [ ! -d $dir ] ; then
			echo "$dir: No such file or directory" 1>&2
			exit 1
		fi
		;;
	esac
	case "$dir" in
		"bogofilter-$bogofilter_version"|"fetchmail-$fetchmail_version")
		echo "Preparing $dir"
		/bin/cp -rp $dir stage
		cd stage/$dir
		echo "Cleaning $dir"
		make -s clean > /dev/null
		make -s distclean > /dev/null
		/bin/rm -rf autom4te.cache .deps
		cd ../..
		;;
		"nssd-$nssd_version"|"courier-imap-$courier_version"|"pam-multi-$pam_multi_version")
		;;
		*)
		/bin/cp -rp $dir stage
		;;
	esac
	case "$dir" in
		"bogofilter-$bogofilter_version"|"fetchmail-$fetchmail_version"|"nssd-$nssd_version"|"courier-imap-$courier_version"|"pam-multi-$pam_multi_version")
		case "$do_archive" in
			gz)
				cd stage
				echo "Archiving $dir.tar.gz in `pwd`"
				tar \
				--exclude="$dir/.git" \
				--exclude="$dir/debian"  \
				--exclude="$dir/RCS" \
				-cf - $dir \
				| gzip -c > $rpmbuild/SOURCES/$dir.tar.gz
				SRC="$rpmbuild/SOURCES/$dir.tar.gz $SRC"
				cd ..
				;;
			bz2)
				cd stage
				echo "Archiving $dir.tar.bz2 in `pwd`"
				tar \
				--exclude="$dir/.git" \
				--exclude="$dir/debian"  \
				--exclude="$dir/RCS" \
				-cf - $dir \
				| bzip2 -c > $rpmbuild/SOURCES/$dir.tar.bz2
				SRC="$rpmbuild/SOURCES/$dir.tar.bz2 $SRC"
				cd ..
				;;
			xz)
				cd stage
				echo "Archiving $dir.tar.xz in `pwd`"
				tar \
				--exclude="$dir/.git" \
				--exclude="$dir/debian"  \
				--exclude="$dir/RCS" \
				-cf - $dir \
				| xz -c > $rpmbuild/SOURCES/$dir.tar.xz
				SRC="$rpmbuild/SOURCES/$dir.tar.xz $SRC"
				cd ..
				;;
		esac
		;;
	esac
done
echo "Preparing indimail-"$version""
/bin/cp -rp indimail-x stage/indimail-"$version"
cd stage/indimail-"$version"
echo "Cleaning indimail-"$version""
make clean > /dev/null
make distclean > /dev/null
/bin/rm -rf autom4te.cache .deps
/bin/rm -rf eps-1.2/autom4te.cache eps-1.2/.deps
cd ..
tar \
	--exclude="indimail-$version/.git" \
	--exclude="indimail-$version/debian"  \
	--exclude="indimail-$version/RCS" \
	-cf - indimail-"$version" \
	| gzip -c > $rpmbuild/SOURCES/indimail-"$version".tar.gz
SRC="$rpmbuild/SOURCES/indimail-"$version".tar.gz $SRC"

echo "Copying permissions files and rpmlintrc"
for i in `get_non_tar_files ../indimail-x/indimail.spec.in`
do
	/bin/cp -p indimail-"$version"/$i $rpmbuild/SOURCES
	SRC="$rpmbuild/SOURCES/$i $SRC"
done
# copy rest of source
for i in $list
do
	echo $i | egrep "nssd|courier-imap|pam-multi" > /dev/null
	if [ $? -eq 0 ] ; then
		continue
	fi
	do_archive="gz"
	echo $i | grep bogofilter > /dev/null
	if [ $? -eq 0 ] ; then
		do_archive="bz2"
	fi
	echo $i | grep fetchmail > /dev/null
	if [ $? -eq 0 ] ; then
		do_archive="xz"
	fi
	dir=`get_dirname $i`
	if [ ! -d $dir ] ; then
		echo "$dir: No such file or directory" 1>&2
		exit 1
	fi
	case "$dir" in
		"bogofilter-$bogofilter_version"|"fetchmail-$fetchmail_version"|"nssd-$nssd_version"|"pam-multi-$pam_multi_version")
		;;
		*)
		echo "Preparing $dir"
		echo "Cleaning $dir"
		/bin/rm -rf $dir/autom4te.cache $dir/.deps
		case "$do_archive" in
			gz)
				echo "Archiving $dir.tar.gz in `pwd`"
				tar \
				--exclude="$dir/.git" \
				--exclude="$dir/debian"  \
				--exclude="$dir/RCS" \
				-cf - $dir \
				| gzip -c > $rpmbuild/SOURCES/$dir.tar.gz
				SRC="$rpmbuild/SOURCES/$dir.tar.gz $SRC"
				;;
			bz2)
				echo "Archiving $dir.tar.bz2 in `pwd`"
				tar \
				--exclude="$dir/.git" \
				--exclude="$dir/debian"  \
				--exclude="$dir/RCS" \
				-cf - $dir \
				| bzip2 -c > $rpmbuild/SOURCES/$dir.tar.bz2
				SRC="$rpmbuild/SOURCES/$dir.tar.bz2 $SRC"
				;;
			xz)
				echo "Archiving $dir.tar.xz in `pwd`"
				tar \
				--exclude="$dir/.git" \
				--exclude="$dir/debian"  \
				--exclude="$dir/RCS" \
				-cf - $dir \
				| xz -c > $rpmbuild/SOURCES/$dir.tar.xz
				SRC="$rpmbuild/SOURCES/$dir.tar.xz $SRC"
				;;
		esac
		;;
	esac
done
dist=`uname -r |cut -d . -f4`
if [ $# -gt 0 ] ; then
	release=$1
else
	if [ -f /usr/bin/vuserinfo ] ; then
		idist=$(rpm -qf /usr/bin/vuserinfo|cut -d- -f3|cut -d. -f3)
		if [ " $dist" = " $idist" ] ; then
			iversion=$(rpm -qf /usr/bin/vuserinfo|cut -d- -f2)
			if [ "$iversion" = "$version" ] ; then
				release=$(rpm -qf /usr/bin/vuserinfo | cut -d- -f3 | cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi
cd ..
echo "Clearing stage directory"
/bin/rm -rf stage
echo -n "Build RPM for indimail-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	tmprel=`cat indimail-x/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " 1.$release" ] ; then
		echo 1.$release > indimail-x/conf-release
		cd indimail-x
		make indimail.spec
		cp indimail.spec /tmp
		cd debian
		make
		cd ../..
	else
		cp indimail-x/indimail.spec /tmp
	fi
	rpmbuild -ba --clean /tmp/indimail.spec
	/bin/rm -f /tmp/indimail.spec
	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
	for i in indimail indimail-devel libindimail
	do
		rpm --addsign $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
	done
	rpm --addsign $rpmbuild/SRPMS/indimail-"$version"-"1.$release".$dist.src.rpm
	echo -n "RPM lint for indimail-"$version"-1."$release" (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		(
		for i in indimail indimail-devel libindimail
		do
			echo $i
			rpmlint $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
			echo ------------------------
		done
		echo indimail-"$version"-"1.$release".$dist.src.rpm
		rpmlint $rpmbuild/SRPMS/indimail-"$version"-"1.$release".$dist.src.rpm
		echo ------------------------
		) 2>&1 | less
	fi
fi
echo -n "Remove Source (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	for i in $SRC
	do
		echo "/bin/rm -f $i"
		/bin/rm -f $i
	done
fi
