#!/bin/sh
version=$(head -1 conf-version)

get_non_tar_files()
{
(
for i in `grep "^Source" $1 | grep -v "\.tar" | awk '{print $2}'`
do
	i=`basename $i`
	echo $i
done
) | sort -u | sed \
	-e 's/%{name}/indimail/g' \
	-e "s/%{version}/$version/g"
}

get_dirname()
{
	echo $1 | sed \
		-e 's}.tar.gz}}g' \
		-e 's}.tar.bz2}}g' \
		-e 's}.tar.xz}}g'
}

if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi

make -s indimail.spec
if [ $? -ne 0 ] ; then
	echo "make failed" 1>&2
	exit 0
fi
if [ -d ../stage ] ; then
	/bin/rm -rf ../stage
fi
mkdir ../stage
cd ..
echo "Preparing indimail-"$version""
/bin/cp -rp indimail-x stage/indimail-"$version"
cd stage/indimail-"$version"
echo "Cleaning indimail-"$version""
make clean > /dev/null
make distclean > /dev/null
/bin/rm -rf autom4te.cache .deps
/bin/rm -rf eps-1.2/autom4te.cache eps-1.2/.deps
cd ..
echo "Archiving indimail-"$version" in `pwd`"
tar \
	--exclude="indimail-$version/.git" \
	--exclude="indimail-$version/debian"  \
	--exclude="indimail-$version/RCS" \
	-cf - indimail-"$version" \
	| gzip -c > $rpmbuild/SOURCES/indimail-"$version".tar.gz
SRC="$rpmbuild/SOURCES/indimail-"$version".tar.gz $SRC"

echo "Copying permissions files and rpmlintrc"
for i in `get_non_tar_files ../indimail-x/indimail.spec.in`
do
	echo "/bin/cp -p indimail-"$version"/$i $rpmbuild/SOURCES"
	/bin/cp -p indimail-"$version"/$i $rpmbuild/SOURCES
	SRC="$rpmbuild/SOURCES/$i $SRC"
done
dist=`uname -r |cut -d . -f4`
if [ $# -gt 0 ] ; then
	release=$1
else
	if [ -f /usr/bin/vuserinfo ] ; then
		idist=$(rpm -qf /usr/bin/vuserinfo|cut -d- -f3|cut -d. -f3)
		if [ " $dist" = " $idist" ] ; then
			iversion=$(rpm -qf /usr/bin/vuserinfo|cut -d- -f2)
			if [ "$iversion" = "$version" ] ; then
				release=$(rpm -qf /usr/bin/vuserinfo | cut -d- -f3 | cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi
cd ..
echo "Clearing stage directory"
/bin/rm -rf stage
echo -n "Build RPM for indimail-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	tmprel=`cat indimail-x/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " 1.$release" ] ; then
		echo 1.$release > indimail-x/conf-release
		cd indimail-x
		make indimail.spec
		cp indimail.spec /tmp
		cd debian
		make
		cd ../..
	else
		cp indimail-x/indimail.spec /tmp
	fi
	rpmbuild -ba --clean /tmp/indimail.spec
	/bin/rm -f /tmp/indimail.spec
	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
	for i in indimail indimail-devel libindimail
	do
		rpm --addsign $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
	done
	rpm --addsign $rpmbuild/SRPMS/indimail-"$version"-"1.$release".$dist.src.rpm
	echo -n "RPM lint for indimail-"$version"-1."$release" (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		(
		for i in indimail indimail-devel libindimail
		do
			echo $i
			rpmlint $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
			echo ------------------------
		done
		echo indimail-"$version"-"1.$release".$dist.src.rpm
		rpmlint $rpmbuild/SRPMS/indimail-"$version"-"1.$release".$dist.src.rpm
		echo ------------------------
		) 2>&1 | less
	fi
fi
echo -n "Remove Source (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	for i in $SRC
	do
		echo "/bin/rm -f $i"
		/bin/rm -f $i
	done
fi
