.TH hostcntrl 8
.SH NAME
hostcntrl \- add, modify, delete hostcntrl entries

.SH SYNOPSYS
\fBhostcntrl\fR [-i\fIhostid\fR | -m \fIhostid\fR | -d \fIhostid\fR] \fIuser@domain\fR

.SH DESCRIPTION
\fBhostcntrl\fR is meant for listing, adding, deleting, modifying user records in the
hostcntrl table for a clustered setup. This is especially useful when you may move a user
from one host to another host in a clustered setup.

.SH OPTIONS

.TP
\fB\-v\fR
Sets verbose operation

.TP
\fB\-s\fR
Shows records pertaining to user@domain in the hostcntrl table.

.TP
\fB\-i\fR \fIhostid\fR
Inserts \fIhostid\fR as the host for user@domain. You can use *@domain to denote a default host for all users.

.TP
\fB\-m\fR
Updates host as \fIhostid\fR for the given user@domain.

.TP
\fB\-d\fR
Deletes the host for the given user@domain.

.TP
\fIuser@domain\fR
The Email ID for the user.

.SH RETURN VALUE
0 for success, 1 for any failure.

.SH "SEE ALSO"
vsmtp(8), vhostid(8), dbinfo(8), IndiMail(7)
