.\" vim: tw=75
.TH indisrvr 8
.SH NAME
indisrvr \- IndiMail administration server

.SH SYNOPSYS
\fBindisrvr\fR \fB\-i\fR \fIIP_Address\fR \fB\-p\fR \fIport\fR \fB\-b\fR \fIbacklog\fR [\fB\-n\fR \fIcertfile\fR]
  [-c cafile -r crlfile] [-t timeoutdata -T timeoutconn]

.SH DESCRIPTION
\fBindisrvr\fR is the administration server for administering IndiMail's
clustered domains. It has a simple mechanism by which administrators can
connect to this server and issue commands to execute any of the IndiMail
programs given above. These commands are issued by the \fBadminclient(8)\fR
program. e.g. To run \fBvadduser\fR on host phoenix2, run \fBadminclient\fR
on any host on the network. \fBindisrvr\fR implements simple authentication
using crypt(3), MD5, SHA256/SHA512. The userid and passwd are maintained in
the table mgmtaccess. A separate password maintenance tool mgmtpass
maintains the passwords in this table. On successful validation of
password, \fBindisrvr\fR executes the specified IndiMail administration
program on the localhost. For security reasons, the list of these
administration programs are hard-coded in the indisrvr executable. On
SIGUSR2, verbose option gets toggled (see -v option below). For a clustered
domain, the table mgmtaccess will be on the hostcntrl db. For a
non-clustered domain, the table mgmtaccess will be on the local MySQL
database.
.PP
Indisrvr uses a privilege table vpriv in MySQl for allowing access to
command and commandLineSwitches. For a clustered domain, the table vpriv
will be on the central database.  For a non-clustered domain, the table
vpriv will be on the local MySQL database. The table vpriv can be
maintained using the \fBvpriv(8)\fR program.
.PP
\fBindisrvr\fR encrypts the communication channel using TLS if \fB\-n\fR
option specifing a certificate is used. One can use use ciphers by setting
\fBTLS_CIPHER_LIST\fR environment variable for TLS protocol TLSv1.2 and
below and \fBTLS_CIPHER_SUITE\fR environment variable for TLS protocol
TLSv1.3 and above. For multiple ciphers, use ':' separated list of ciphers.
See openssl-ciphers(1ossl).

The following command runs the command vadduser with arguments test@indi.com password.
.EX
adminclient -h phoenix2 -p  4000 -u admin -P adminpass -c ''vadduser test@indi.com password''
.EE

.SH OPTIONS
.TP
\fB\-v\fR
Sets verbose option.
.TP
\fB\-i\fR \fIIP_Address\fR
The IP address on which indisrvr needs to bind. Useful if a host has
multiple IP addresses.
.TP
\fB\-p\fR \fIport\fR
A TCP/IP port or service in /etc/services on which indisrvr needs to bind.
.TP
\fB\-b\fR \fIbacklog\fR
Max backlog to be maintained after which the client should get connection
refused
.TP
\fB\-d\fR \fIcertdir\fR
certificate directory for RSA/DH parameter files
.TP
\fB\-n\fR \fIcertfile\fR
A PEM certificate causes indisrvr to negotiate TLS encryption with clients.
.TP
-\fBc\fR \fIcafile\fR
Specify \fIcafile\fR as the file containing CA certificates. Sometimes,
special CA certificates are needed if an intermediate certificate used
by your issuing CA expires. Note that the file given with -c is passed
to SSL_CTX_load_verify_locations and thus may contain several CA
certificates, which will be used during SSL connection negotiation to
close any gap in the certificate chain.
.TP
-\fBr\fR \fIcrlfile\fR
A list of Certificate Revocation Lists (CRLs). If present it
should contain the CRLs of the CAs in \fIcafile\fR and client certs that
will be checked for revocation.
.TP
\fB\-t\fR \fItimeoutdata\fR
Quit if read or write to/from commands or application exceeds
\fItimeoutdata\fR seconds.
.TP
\fB\-T\fR \fItimeoutconn\fR
Timeout on TLS/SSL accept if attempt exceeds \fItimeoutconn\fR seconds.

.SH RETURN VALUE
Always returns non-zero status, which means the server died due to some
reasons. Most likely of a bug. Will also return on SIGTERM with exit
status=0.

.SH "SEE ALSO"
adminclient(8), mgmtpass(8), vpriv(8), openssl-ciphers(1ossl)
