.\" vim: tw=75
.TH vcfilter 1
.SH NAME
vcfilter \- create, modify, delete vfilters

.SH SYNOPSYS
.PP
\fBvcfilter\fR [\fIoptions\fR] \fIemailid\fR

.SH DESCRIPTION
\fBvcfilter\fR is a utility for creating, modifying, deleting IndiMail's
powerful filter called as vfilter. Currently, \fBvcfilter\fR allows maximum
of 255 filters to be created.

\fBvcfilter\fR has setuid bit set and can be run by the root user, by user
having uid/gid of the domain in @sysconfdir@/users/assign or if the user
has the gid of the domain as a supplementary group.

.SH OPTIONS  (for filters)
.TP
\fB\-v\fR
Sets verbose option

.TP
\fB\-C\fR
Connect to cluster. Allows vcfilter to operate on users belonging to any
cluster rather than just the local users.

.TP
\fB\-s\fR
Show Filters

.TP
\fB\-r\fR
unformatted display (for -s option)

.TP
\fB\-i\fR
add filter

.TP
\fB\-d\fR \fIfilter_no\fR
delete filter(s)

.TP
\fB\-u\fR \fIfilter_no\fR
update filter

.TP
\fB\-t\fR \fIfilter_name\fR
Textual name for the filter

.TP 
\fB\-c\fR
Comparison with the headers to make. This could be one of the following
textual name or number.

 0 - Equals
 1 - Contains
 2 - Does not contain
 3 - Starts with
 4 - Ends with
 5 - Sender not in address book
 6 - My ID not in To, Cc, Bcc
 7 - Numerical or Logical Expression
     %p in keyword is replaced with value of data of the Header Field
 8 - RegExp

.TP
\fB\-h\fR
header value. textual name or number denoting the following

 -1  - If comparision (-c option) is 5 or 6
  0  - Return-Path                       1 - From
  2  - Subject                           3 - To
  4  - Cc                                5 - Bcc
  6  - Reply-To                          7 - Date
  8  - Sender                            9 - User-Agent
  10 - Message-Id                       11 - MIME-Version
  12 - Content-Type                     13 - Content-Transfer-Encoding
  14 - Precedence                       15 - Organization
  16 - Errors-To                        17 - List-Id
  18 - Importance                       19 - Mailing-List
  20 - X-Sender                         21 - X-Mailing-List
  22 - X-ML-Name                        23 - X-List
  24 - X-Loop                           25 - X-BeenThere
  26 - X-Sequence                       27 - X-Mailer
  28 - X-QHPSI                          29 - X-Priority
  30 - X-Mailer                         31 - X-Spam-Status
  32 - X-Spam-Rating                    33 - X-Bogosity
  34 - Received                         35 - X-Quarantine
  36 - Domainkey-Signature              37 - DKIM-Signature
  38 - DKIM-Status                      39 - Domainkey-Status
  40 - X-Forwarded-To                   41 - X-Forwarded-For
  42 - Return-Receipt-To                43 - Dispostion-Notification-To
  44 - Disposition-Notification-Options 45 - Original-Recipient

You can add your own headers by appending headers to
@sysconfdir@/headerlist.

.TP
\fB\-k\fR \fIkeyword\fR
A keyword or string which will be used in comparison with the header value
(depending on -c option). The string should be a NULL "" string if -c
option is either 5 or 6. The keyword can also be any Regular Expression
(i.e. *, ? [], etc) if comparison equals 7..

.TP
\fB\-f\fR \fIFolder\fR
Folder to which the mail should be delivered if a filter match occurs. This
can be the keyword Inbox to have the email delivered to the inbox (as it
was originally). This can be the Trash folder in case the mail needs to be
rejected. It can be /NoDeliver if the mail needs to be discarded
completely.

.TP
\fB\-b\fR \fIbounce_action\fR
 bounce_action can be one of the four numbers
 0 - Do not bounce
 1 - Bounce mail to sender with the following custom message
     "Hi. This is the IndiMail MDA for <domain_name>.
     "I'm afraid I cannot accept your message as it violates a system policy"
     "set by the administrator. Sorry that I cannot accept your email"
 2 - Forward mail to address following the number. An ampersand
     '&' sign must separate the number and the address.
     i.e. 2&editor@indimail.org will forward all emails
     to the mailbox editor@indimail.org (replace '&' with '|'
     to feed the message through a program)
 3 - Same as above but bounce as well.

.SH RETURN VALUE
Returns 0 for success, 1 for any failure.

.SH "SEE ALSO"
vfilter(8), vdelivermail(8)
