.\" vim: tw=75
.TH vmoduser 1
.SH NAME
vmoduser \- Modify virtual user attributes

.SH SYNOPSYS
\fBvmoduser\fI [\fIoptions\fR] \fIemail_addr\fR

.SH DESCRIPTION
.PP
.B vmoduser
modifies attributes of an email account by modifying fields in the
authentication tables indimail or indibak. \fBvmoduser\fR has the setuid
bit set to root and must be run as root or indimail user.

.SH POST HANDLE
If the environment variable POST_HANDLE is set, \fBvmoduser\fR executes the
program defined by the POST_HANDLE environment variable, passing all
arguments passed to vmoduser. If POST_HANDLE is not defined, the
program/script LIBEXECDIR/vmoduser will be executed.

.SH OPTIONS
.PP
.TP 3
\fB\-v\fR
Sets verbose mode

.TP 3
\fB\-n\fR
Toggles between Inactive and Active state for the user
i.e. Moves the user between indimail and indibak

.TP 3
\fB\-q\fR \fIquota\fR
Changes the quota for the user. Changes the field pw_shell in indimail or
indibak.  You can also use +\fIquota\fR to increase the existing quota by
amount specified by \fIquota\fR. You can also use -\fIquota\fR to decrease
the existing quota by amount specified by \fIquota\fR. You can use k/K,
m/M, g/G for kibibytes, mebibytes and gibibytes respectively, when
specifying a value for \fIquota\fR.

If the domain has domain limits set using vmoddomlimits(1), then domain
limits apply. Also, this option will not be allowed if permission for
modifying quota is disabled in domain limits.

.TP 3
\fB\-c\fR \fIcomment\fR
Changes the gecos (comment) field for the user. Changes the field pw_gecos
in indimail or indibak.

.TP 3
\fB\-P\fR \fIclear_text\fR
Sets an encrypted password for the user after encrypting the clear text
password given on the command line. Changes the field pw_passwd in indimail
or indibak. Changes the pw_passwd field in indimail/indibak tables.

.TP 3
\fB\-e\fR
Changes the passwd for the user as given after '\fB\-P\fR'
argument (without performing any encryption). It is expected to supply a
crypted password using crypt(3) library call. You can use this to set
clear-text password for CRAM/SCRAM methods. Changes the \fIpw_passwd\fR
field in indimail/indibak tables.

.TP 3
\fB\-h\fR \fIhash\fR
Specifiy hash which is one of DES, MD5, SHA-256, SHA-512

.nf
.ta 5c 10c
HASH        	Value	Description
DES	0	DES encryption (shouldn't be used)
MD5	1	MD5 encryption (shouldn't be used)
SHA-256	2	SHA256 encryption
SHA-512	3	SHA512 encryption
.fi

You can also set the environment variable \fBPASSWORD_HASH\fR to set the
encryption method. The -h argument overrides the environment variable
\fBPASSWORD_HASH\fR. The value of \fBPASSWORD_HASH\fR environment variable
identifies the encryption method used and this then determines how the rest
of the password string is interpreted. The following values of
\fBPASSWORD_HASH\fR are supported:

.nf
.ta 5c 10c
PASSWORD_HASH Value	Description
0	DES encryption (shouldn't be used)
1	MD5 encryption (shouldn't be used)
2	SHA256 encryption
3	SHA512 encryption
.fi
.RE

.TP 3
\fB\-m\fR \fISCRAM_method\fR
Sets the SCRAM method for encryption. This will set SCRAM password in the
\fIscram\fR field in indimail/indibak tables.

.nf
.ta 5c 10c
SCRAM method	Value
SCRAM-SHA-1	SHA1 encryption suitable for SCRAM-SHA-1.
SCRAM-SHA-256	SHA256 encryption suitable for SCRAM-SHA-256.
.fi
.RE

.TP 3
\fB\-C\fR
Sets up authentication suitable for CRAM-MD5, CRAM-SHA1, CRAM-SHA224,
CRAM-SHA256, CRAM-SHA384, CRAM-SHA512, CRAM-RIPEMD and DIGEST-MD5 methods.
This works by storing the clear text credentials in the database. if the
\-\fIm\fR option is selected, this will additionally store a hex-encoded
salted password for SCRAM methods, which can be used instead of clear text
passwords by clients (for SCRAM authentication).

.TP 3
\fB\-S\fR \fIsalt\fR
Specify a base64 encoded salt to be used when generating SCRAM password. If
not specified, this will be generated using libsodium/gsasl.

.TP 3
\fB\-I\fR \fIiteration\fR
Specify the iteration count to be used when generating SCRAM password. The
default is 4096.

.TP 3
\fB\-D\fR \fIdate_format\fR
Delivery to a date folder instead of Maildir (Inbox) as per format
specification \fIdate_format\fR. \fBvdelivermail\fR(8) uses
\fBstrftime\fR(3) to process the date format. This format is maintained in
the file \fIfolder.dateformat\fR in user's Maildir.

.EX
The format %b-%Y will cause emails to be delivered to Apr-2014 if the
delivery date happens to be anytime in Apr 2014
.EE

.TP 3
\fB\-l\fR \fIvacation_messsage_file\fR
Sets up autoresponder for the user. It creates .qmail file in user's
homedir containing path to the autoresponder program vacation. If
vacation_message_file is specified as '\fB-\fR', autoresponder is removed.
If it is specified as '\fB+\fR', the text for autoresponder is taken from
STDIN. Any other value is taken as a file containing text for the
autoresponder.

.PP
The following options are bit flags in the gid int field. (pw_gid in
indimail or indibak)

.TP 3
\fB\-t\fR
Toggle the bit flags in the gid int field

.TP 3
\fB\-u\fR
Set no dialup flag.

.TP 3
\fB\-d\fR
Set no password changing flag for the user

.TP 3
\fB\-p\fR
Set no POP3 access flag.

.TP 3
\fB\-w\fR
Set no web mail access flag.

.TP 3
\fB\-i\fR
Set no IMAP4 access flag.

.TP 3
\fB\-b\fR
Set bounce mail flag.

.TP 3
\fB\-r\fR
Set no external relay flag.

.TP 3
\fB\-a\fR
Grant administrator privileges.

.TP 3
\fB\-0\fR
Reserved for future use.

.TP 3
\fB\-1\fR
Reserved for future use.

.TP 3
\fB\-2\fR
Reserved for future use.

.TP 3
\fB\-3\fR
Reserved for future use.

.TP 3
\fB\-x \fR
Clear all flags
.PP
The values of pw_gid corresponding to the above options are as below.

.nf
.ta 5c 10c
Option	Value

NO_PASSWD_CHNG	0x01
NO_POP	0x02
NO_WEBMAIL	0x04
NO_IMAP	0x08
BOUNCE_MAIL	0x10
NO_RELAY	0x20
NO_DIALUP	0x40
QA_ADMIN	0x80
V_USER0	0x100
V_USER1	0x200
V_USER2	0x400
V_USER3	0x800
.fi

.SH RETURN VALUES
0 in case of success and non-zero in case of any failure.

.SH "SEE ALSO"
vsetuserquota(1), vpasswd(1), vmoddomlimits(1), resetquota(8),
vdelivermail(8), strftime(3), incrypt(1), crypt(3), gsasl(1)
