.TH vpasswd 1
.SH NAME
vpasswd \- change passwd for virtual domain user

.SH SYNOPSYS
.B vpasswd
[
.I options
]
.I email_address
[
.I password
] 

.SH DESCRIPTION
\fBvpasswd\fR changes a virtual domain email users password. The program
must be run as root or as the indimail user. It uses \fBcrypt(3)\fR routine
to encrypt the password. You can use the -h argument to specify the hash
method for encryption (See Below). You can also set the environment
variable \fBPASSWORD_HASH\fR to set the encryption method. The -h argument
overrides the environment variable \fBPASSWORD_HASH\fR. The value of
\fBPASSWORD_HASH\fR environment variable identifies the encryption method
used and this then determines how the rest of the password string is
interpreted. The following values of \fBPASSWORD_HASH\fR are supported:

.RS
.nf
.ta 5c 10c
PASSWORD_HASH Value	Description
0	DES encryption (shouldn't be used)
1	MD5 encryption (shouldn't be used)
2	SHA256 encryption
3	SHA512 encryption
.fi
.RE

.SH POST HANDLE
If the environment variable POST_HANDLE is set, \fBvpasswd\fR executes the
program defined by the POST_HANDLE environment variable, passing
\fIemail_address\fR as a parameter. If POST_HANDLE is not defined, the
program/script LIBEXECDIR/vpasswd will be executed with
\fIemail_address\fR as a parameter.

.SH OPTIONS
.TP
\fB\-e\fR
Set the encrypted Password field
This options disables the internal encryption routine which encrypts the
password provided on the command line. This option sets the encrypted
password field exactly as given on the command line without any encryption.
It expects you to give a standard encrypted password or you can use
this to set plaintext/salted password for CRAM, SCRAM authentication
methods.

.TP
\fB\-h\fR \fIhash\fR
Specifiy hash which is one of DES, MD5, SHA-256, SHA-512,
.RS
.nf
.ta 5c 10c
HASH        	Value	Description
DES	0	DES encryption (shouldn't be used)
MD5	1	MD5 encryption (shouldn't be used)
SHA-256	2	SHA256 encryption
SHA-512	3	SHA512 encryption
.fi
.RE

.TP
\fB\-m\fR \fIscram\fR
Specifiy scram method which is one of SCRAM-SHA-1, SCRAM-SHA-256
.RS
.nf
.ta 5c 10c
SCRAM method	Description
-------------	-----------
SCRAM-SHA-1	SHA1 encryption suitable for SCRAM-SHA-1.
SCRAM-SHA-256	SHA256 encryption suitable for SCRAM-SHA-256.
.fi
.RE

.TP
\fB\-C\fR
Sets up authentication suitable for CRAM-MD5, CRAM-SHA1, CRAM-SHA224,
CRAM-SHA256, CRAM-SHA384, CRAM-SHA512, CRAM-RIPEMD and DIGEST-MD5 methods.
This will additionally store the clear text credentials and a hex-encoded
salted password for SCRAM methods. This allows the above mentioned
authentication mechanisms to work along with the PLAIN, LOGIN and the SCRAM
methods.

.TP 3
\fB\-S\fR \fIsalt\fR
Specify a base64 encoded salt to be used when generating SCRAM password. If
not specified, this will be generated using libsodium/gsasl. Here base64
implies characters [0-9], [a-z], [A-Z] and the two characters [./].

.TP
\fB\-I\fR \fIiteration\fR
Specify the iteration count to be used when generating SCRAM password. The
default is 4096.

.TP
\fB\-r\fR \fIlength\fR
Generate a random password of length \fIlength\fR characters. This option
is ignored when \fIpassword\fR is supplied on the command line.

.TP
\fB\-v\fR
Set verbose mode.

.TP
\fIemail_address\fR
username including the domain component

.TP
[\fIpassword\fR]
Set the password on the command line. If the password is not supplied on
the command line then user is prompted for the password. The password must
be entered correctly twice in order to be accepted.

.SH RETURN VALUE
0 if all steps were successful, non-zero otherwise. If any of the steps
fail, a diagnostic message is printed.

.SH "SEE ALSO"
vmoduser(1), vadduser(1), vmoduser(1), gsasl(1),
gsasl_scram_secrets_from_password(3)
