.\" vim: tw=75
.TH vrenameuser 1
.SH NAME
vrenameuser \- change email address of a virtual user to a new email
address

.SH SYNOPSYS
\fBvrenameuser\fR [\fIoptions\fR] \fIold_email_address\fR \fInew_email_address\fR

.SH DESCRIPTION
.PP
\fBvrenameuser\fR changes the email address of an existing virtual domain
user to a new email address. This can be used to either change the username
or to move the user to a new virtual domain lying on the same host.
vrenameuser changes only the pw_name and pw_domain component, and doesn't
change attributes like pw_gecos, pw_dir, etc. But can be used in
conjunction with vmoveuser, vmoduser it can be used to change the homedir,
gecos also. \fBvrenameuser\fR has setuid bit to root and can be run by the
root or indimail user. If the uid of domain in \fIold_email_address\fR is
different from the domain in \fInew_email_address\fR in
\fI@sysconfdir@/users/assign\fR, \fBvrenameuser\fR will run with root
privileges. If the uid of both the domains is same, then
\fBvrenamedomain\fR runs with the uid of the caller.

.SH POST HANDLE
If the environment variable \fBPOST_HANDLE\fR is set, \fBvrenameuser\fR
executes the program defined by the \fBPOST_HANDLE\fR environment variable.
If POST_HANDLE is not defined, the program @libdexecdir@/vrenameuser will
be executed. Additionally if the uid of domain in \fIold_email_address\fR
is different from the domain in \fInew_email_address\fR in
\fI@sysconfdir@/users/assign\fR, the \fBPOST_HANDLE\fR program root
privileges will be dropped and the program will run with the original uid
of the caller. If \fBPOST_HANDLE\fR is not defined and if the uid of domain
in \fIold_email_address\fR is different from the domain in
\fInew_email_address\fR in \fI@sysconfdir@/users/assign\fR,
\fBPOST_HANDLE\fR program will run with root privileges. If the uids are
same, then the \fBPOST_HANDLE\fR program will run with the original uid of
the caller. The POST_HANDLE program is executed with
\fIold_email_address\fR and \fInew_email_address\fR as command line
arguments. \fBPOST_HANDLE\fR program is executed as the last step after all
earlier steps have been successful.

.SH OPTIONS
.PP
.TP
\fB\-V\fR
Print Version Numbers
.TP
\fB\-v\fR
Set verbose mode
.TP
\fIold_email_address\fR
Current email address of the user.
.TP
\fInew_email_address\fR
Desired new email address for the user.

.SH RETURN VALUE
0 if successful, 1 in case of any failure.

.SH "SEE ALSO"
vmoveuser(1)
