#!/bin/sh
rcsflag=0
version=$(head -1 conf-version)

verbose=0
clean=""
while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
	;;
    *) optarg=
	;;
    esac

    case "$1" in
    --release=*)
	release=$optarg
    ;;
    --verbose)
	verbose=1
    ;;
    --clean)
	clean="--clean"
    ;;
    *)
    echo "invalid option [$1]"
    read key
    exit 1
    ;;
    esac

    shift
done

if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi

copy_src=0
echo -n "Copy Source Files - "
read key
if [ " $key" = " y" -o " $key" = " Y" ] ; then
	copy_src=1
fi

make -s ircube.spec
if [ $? -ne 0 ] ; then
	echo "make failed" 1>&2
	exit 0
fi

if [ $copy_src -eq 1 ] ; then
	if [ -d ../stage ] ; then
		/bin/rm -rf ../stage
	fi
	mkdir ../stage
	cd ..
	echo "Versioning ircube-$version"
	cp -rp ircube-x stage/ircube-$version
	rm -f stage/ircube-$version/catChangeLog
	cp ircube-x/catChangeLog stage/ircube-$version
	cd stage/ircube-$version
	make -s clean
	make -s distclean
	/bin/rm -rf autom4te.cache
	cd ..
	echo "Archiving "ircube"-"$version".tar.gz in `pwd`"
	tar \
		--exclude=""ircube"-"$version"/.git" \
		--exclude=""ircube"-"$version"/debian"  \
		--exclude=""ircube"-"$version"/RCS" \
		-cf - ircube-$version \
		| gzip -c > $rpmbuild/SOURCES/"ircube"-"$version".tar.gz
	cd ..
	echo "Clearing stage directory"
	/bin/rm -rf stage
else
	cd ..
fi
dist=`uname -r |cut -d . -f4`
if [ -z "$release" ] ; then
	if [ -d /usr/share/roundcubemail/plugins/iwebadmin ] ; then
		bdist=$(rpm -qf /usr/share/roundcubemail/plugins/iwebadmin|cut -d- -f3|cut -d. -f3)
		if [ " $dist" = " $bdist" ] ; then
			bversion=$(rpm -qf //usr/share/roundcubemail/plugins/iwebadmin|cut -d- -f2)
			if [ "$bversion" = "$version" ] ; then
				release=$(rpm -qf /usr/share/roundcubemail/plugins/iwebadmin|cut -d- -f3|cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi
echo -n "Build RPM for ircube-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	tmprel=`cat ircube-x/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " 1.$release" ] ; then
		echo 1.$release > ircube-x/conf-release
		cd ircube-x
		make ircube.spec
		cp ircube.spec /tmp
		cd debian
		make
		cd ../..
	else
		cp ircube-x/ircube.spec /tmp
	fi
	if [ $verbose -eq 0 ] ; then
		rpmbuild -ba $clean --quiet /tmp/ircube.spec
	else
		rpmbuild -ba $clean /tmp/ircube.spec
	fi
	/bin/rm -f /tmp/ircube.spec
	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
	rpm --addsign $rpmbuild/RPMS/$build_arch/ircube-"$version"-"1.$release".$dist.$build_arch.rpm
	rpm --addsign $rpmbuild/SRPMS/ircube-"$version"-"1.$release".$dist.src.rpm
	echo -n "RPM lint for ircube-"$version"-1."$release" (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		(
		echo ircube
		rpmlint $rpmbuild/RPMS/$build_arch/ircube-"$version"-"1.$release".$dist.$build_arch.rpm
		echo ------------------------
		echo ircube-"$version"-"1.$release".$dist.src.rpm
		rpmlint $rpmbuild/SRPMS/ircube-"$version"-"1.$release".$dist.src.rpm
		echo ------------------------
		) 2>&1 | less
	fi
fi
if [ $copy_src -eq 1 ] ; then
	echo -n "Remove Source (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		echo "/bin/rm -f $rpmbuild/SOURCES/ircube-$version"
		/bin/rm -f $rpmbuild/SOURCES/ircube-$version
	fi
fi
