#!/bin/sh
set -x
rcsflag=0
make clean
make distclean
/bin/rm -r autom4te.cache
ver=1.0
cd ..
if [ -f $HOME/.rpmmacros ] ; then
	topdir=`grep ^%_topdir $HOME/.rpmmacros|awk '{print $2}'`
else
	topdir=$HOME/rpmbuild
fi
tar cf - ircube-$ver |gzip -c > $topdir/SOURCES/ircube-$ver.tar.gz
cd ircube-$ver
rpmbuild -bb --clean ircube.spec
