#!/bin/sh
# $Log: create_rpm,v $
#
# $Id: create_rpm,v 1.6 2020-05-25 23:14:02+05:30 Cprogrammer Exp mbhangui $
#
curdir=`pwd`
version=$(cat conf-version)

if [ -d ../stage ] ; then
	/bin/rm -rf ../stage
fi
mkdir ../stage
cd ..
cp -rp bogofilter-$version stage
cd stage/bogofilter-$version
echo "Cleaning bogofilter-$version"
make -s clean > /dev/null
make -s distclean > /dev/null
if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi
/bin/rm -rf autom4te.cache .deps
cd ..
tar \
	--exclude="bogofilter-$version/.git" \
	--exclude="bogofilter-$version/debian"  \
	--exclude="bogofilter-$version/RCS" \
	-cf - bogofilter-"$version" \
	| bzip2 -c > $rpmbuild/SOURCES/bogofilter-"$version".tar.bz2
dist=`uname -r |cut -d . -f4`
if [ $# -gt 0 ] ; then
	release=$1
else
	if [ -f /usr/bin/bogofilter ] ; then
		bdist=$(rpm -qf /usr/bin/bogofilter|cut -d- -f3|cut -d. -f3)
		if [ " $dist" = " $bdist" ] ; then
			bversion=$(rpm -qf /usr/bin/bogofilter|cut -d- -f2)
			if [ "$bversion" = "$version" ] ; then
				release=$(rpm -qf /usr/bin/bogofilter | cut -d- -f3 | cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi
cd ..
echo "Clearing stage directory"
/bin/rm -rf stage
echo -n "Build RPM for bogofilter-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	tmprel=`cat bogofilter-$version/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " 1.$release" ] ; then
		echo 1.$release > bogofilter-$version/conf-release
		cd bogofilter-$version
		make bogofilter.spec
		cp bogofilter.spec /tmp
		cd debian
		make
		cd ../..
	else
		cp bogofilter-$version/bogofilter.spec /tmp
	fi
	rpmbuild -ba --clean /tmp/bogofilter.spec
	/bin/rm -f /tmp/bogofilter.spec
	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
	rpm --addsign $rpmbuild/RPMS/$build_arch/bogofilter-"$version"-"1.$release".$dist.$build_arch.rpm
	rpm --addsign $rpmbuild/SRPMS/bogofilter-"$version"-"1.$release".$dist.src.rpm
	echo -n "RPM lint for bogofilter-"$version"-1."$release" (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		(
		echo bogofilter
		rpmlint $rpmbuild/RPMS/$build_arch/bogofilter-"$version"-"1.$release".$dist.$build_arch.rpm
		echo ------------------------
		echo bogofilter-"$version"-"1.$release".$dist.src.rpm
		rpmlint $rpmbuild/SRPMS/bogofilter-"$version"-"1.$release".$dist.src.rpm
		echo ------------------------
		) 2>&1 | less
	fi
fi
echo -n "Remove Source (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	echo "/bin/rm -f $rpmbuild/SOURCES/bogofilter-$version.tar.bz2"
	/bin/rm -f $rpmbuild/SOURCES/bogofilter-$version.tar.bz2
fi
