#!/bin/sh
if [ ! -f /etc/debian_version ] ; then
	echo "Not a debian or ubuntu distribution" 1>&2
	exit 1
fi
iwebadmin_version=$(cat conf-version)

make -s debian/Makefile
make -s -C debian
/bin/rm -rf $HOME/stage/iwebadmin-$iwebadmin_version
mkdir -p    $HOME/stage/iwebadmin-$iwebadmin_version
cp -rp .    $HOME/stage/iwebadmin-$iwebadmin_version
cd          $HOME/stage/iwebadmin-$iwebadmin_version
dpkg-buildpackage -tc -b
/bin/rm -rf $HOME/stage/iwebadmin-$iwebadmin_version
ls -lt $HOME/stage
