#!/bin/sh
# $Log: catChangeLog,v $
#
# utility to append changelog to indimail.spec
#
#
# $Id: catChangeLog,v 1.4 2020-05-30 16:43:18+05:30 Cprogrammer Exp mbhangui $
#
flag=0
if [ $# -eq 1 ] ; then
	file=$1
else
	file=doc/ChangeLog
fi
cat $file|while read line
do
	echo "$line"|grep "^*" > /dev/null
	if [ $? -eq 0 -a $flag -ne 0 ] ; then
		break
	fi
	echo "$line" | grep "^[0-9]*/.*/.*" > /dev/null # skip dates
	if [ $? -eq 0 ] ; then
		continue
	fi
	if [ $flag -eq 0 ] ; then # first line
		echo "* `date +"%a %b %d %Y %H:%M:%S %z"` indium@indimail.org" @version@-@release@%{?dist}
		flag=1
		continue
	elif [ $flag -eq 1 ] ; then
		echo "$line"
		flag=2
		continue
	fi
	echo "$line" |egrep "^- [0-9]|^[0-9]" > /dev/null
	if [ $? -eq 0 ] ; then
		echo "$line"
	elif [ -n "$line" ] ; then
		echo "    $line"
	fi
done

