#!/bin/sh
curdir=`pwd`
version=$(cat conf-version)

if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi

copy_src=0
echo -n "Copy Source Files - "
read key
if [ " $key" = " y" -o " $key" = " Y" ] ; then
	copy_src=1
fi

make -s indium.spec
if [ $? -ne 0 ] ; then
	echo "make failed" 1>&2
	exit 0
fi

if [ $copy_src -eq 1 ] ; then
	if [ -d ../stage ] ; then
		/bin/rm -rf ../stage
	fi
	mkdir ../stage
	cd ..
	echo "Versioning indium-$version"
	cp -rp indium-x stage/indium-$version
	cd stage/indium-$version
	echo "Cleaning indium-$version"
	make -s clean > /dev/null
	make -s distclean > /dev/null
	/bin/rm -rf autom4te.cache .deps
	cd ..
	echo "Archiving indium-$version.tar.gz in `pwd`"
	tar \
		--exclude="indium-$version/.git" \
		--exclude="indium-$version/debian"  \
		--exclude="indium-$version/RCS" \
	-cf - indium-"$version" \
		| gzip -c > $rpmbuild/SOURCES/indium-"$version".tar.gz
	echo "cp indium-$version/indium-rpmlintrc $rpmbuild/SOURCES"
	cp indium-$version/indium-rpmlintrc $rpmbuild/SOURCES
	cd ..
	echo "Clearing stage directory"
	/bin/rm -rf stage
else
	cd ..
fi
dist=`uname -r |cut -d . -f4`
if [ $# -gt 0 ] ; then
	release=$1
else
	if [ -f /usr/bin/indium ] ; then
		bdist=$(rpm -qf /usr/bin/indium|cut -d- -f3|cut -d. -f3)
		if [ " $dist" = " $bdist" ] ; then
			bversion=$(rpm -qf /usr/bin/indium|cut -d- -f2)
			if [ "$bversion" = "$version" ] ; then
				release=$(rpm -qf /usr/bin/indium|cut -d- -f3|cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi
echo -n "Build RPM for indium-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	tmprel=`cat indium-x/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " 1.$release" ] ; then
		echo 1.$release > indium-x/conf-release
		cd indium-x
		make indium.spec
		cp indium.spec /tmp
		cd debian
		make
		cd ../..
	else
		make -s -C indium-x indium.spec
		cp indium-x/indium.spec /tmp
	fi
	rpmbuild -ba --clean /tmp/indium.spec
	/bin/rm -f /tmp/indium.spec
	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
	rpm --addsign $rpmbuild/RPMS/$build_arch/indium-"$version"-"1.$release".$dist.$build_arch.rpm
	rpm --addsign $rpmbuild/SRPMS/indium-"$version"-"1.$release".$dist.src.rpm
	echo -n "RPM lint for indium-"$version"-1."$release" (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		(
		echo indium
		rpmlint $rpmbuild/RPMS/$build_arch/indium-"$version"-"1.$release".$dist.$build_arch.rpm
		echo ------------------------
		echo indium-"$version"-"1.$release".$dist.src.rpm
		rpmlint $rpmbuild/SRPMS/indium-"$version"-"1.$release".$dist.src.rpm
		echo ------------------------
		) 2>&1 | less
	fi
fi
if [ $copy_src -eq 1 ] ; then
	echo -n "Remove Source (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		echo "/bin/rm -f $rpmbuild/SOURCES/indium-$version.tar.bz2"
		/bin/rm -f $rpmbuild/SOURCES/indium-$version.tar.bz2
		echo "/bin/rm -f $rpmbuild/SOURCES/indium-rpmlintrc"
		/bin/rm -f $rpmbuild/SOURCES/indium-rpmlintrc
	fi
fi
