#!/bin/sh
if [ ! -f /etc/debian_version ] ; then
	echo "Not a debian or ubuntu distribution" 1>&2
	exit 1
fi
indium_version=$(cat conf-version)

make -s debian/Makefile
make -s -C debian
echo "Cleaning Stage"
/bin/rm -rf $HOME/stage/indium-$indium_version
echo "Copying Stage"
mkdir -p    $HOME/stage/indium-$indium_version
cp -rp .    $HOME/stage/indium-$indium_version
cd          $HOME/stage/indium-$indium_version
dpkg-buildpackage -tc -b
if [ $? -eq 0 ] ; then
	/bin/rm -rf $HOME/stage/indium-$indium_version
	ls -lt $HOME/stage
fi
