#!/bin/sh
if [ ! -f /etc/debian_version ] ; then
	echo "Not a debian or ubuntu distribution" 1>&2
	exit 1
fi
pam_multi_version=$(cat ../pam-multi-x/conf-version)
nssd_version=$(cat ../nssd-x/conf-version)

make -s debian/Makefile
make -s -C debian
/bin/rm -rf           $HOME/stage/indimail-auth
mkdir -p              $HOME/stage/indimail-auth
cp -rp ../nssd-x      $HOME/stage/indimail-auth/nssd-$nssd_version
cp -rp ../pam-multi-x $HOME/stage/indimail-auth/pam-multi-$pam_multi_version
cp -rp debian         $HOME/stage/indimail-auth
cd                    $HOME/stage/indimail-auth
dpkg-buildpackage -tc -b
/bin/rm -rf           $HOME/stage/indimail-auth
ls -lt $HOME/stage
