#!/bin/sh
# $Log: create_rpm,v $
#
# $Id: create_rpm,v 1.6 2020-05-25 23:14:02+05:30 Cprogrammer Exp mbhangui $
#
curdir=`pwd`
version=$(cat conf-version)

if [ -f /etc/debian_version ] ; then
	echo "you can't do rpmbuild on an insane system" 1>&2
	exit 1
fi

verbose=0
while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
	;;
    *) optarg=
	;;
    esac

    case "$1" in
    --verbose)
	verbose=1
    ;;
    *)
    echo "invalid option [$1]"
    read key
    usage 1
    ;;
    esac

    shift
done

if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi

copy_src=0
echo -n "Copy Source Files - "
read key
if [ " $key" = " y" -o " $key" = " Y" ] ; then
	copy_src=1
fi
make -s indimail-spamfilter.spec
if [ $? -ne 0 ] ; then
	echo "make failed" 1>&2
	exit 1
fi

if [ $copy_src -eq 1 ] ; then
	if [ -d ../stage ] ; then
		/bin/rm -rf ../stage
	fi
	mkdir ../stage
	cd ..
	echo "Versioning indimail-spamfilter-$version"
	cp -rp bogofilter-x stage/indimail-spamfilter-$version
	cd stage/indimail-spamfilter-$version
	echo "Cleaning indimail-spamfilter-$version"
	make -s clean > /dev/null
	make -s distclean > /dev/null
	/bin/rm -rf autom4te.cache .deps
	cd ..
	echo "Archiving indimail-spamfilter-$version.tar.bz2 in `pwd`"
	tar \
		--exclude="indimail-spamfilter-$version/.git" \
		--exclude="indimail-spamfilter-$version/debian"  \
		--exclude="indimail-spamfilter-$version/RCS" \
		-cf - indimail-spamfilter-"$version" \
		| bzip2 -c > $rpmbuild/SOURCES/indimail-spamfilter-"$version".tar.bz2
	for i in rpmlintrc permissions.easy permissions.secure permissions.paranoid
	do
		echo "cp -p indimail-spamfilter-$version/indimail-spamfilter-$i $rpmbuild/SOURCES"
		cp -p indimail-spamfilter-$version/indimail-spamfilter-$i $rpmbuild/SOURCES
	done
	cd ..
	echo "Clearing stage directory"
	/bin/rm -rf stage
else
	cd ..
fi
dist=`uname -r |cut -d . -f4`
if [ $# -gt 0 ] ; then
	release=$1
else
	if [ -f /usr/bin/bogofilter ] ; then
		bdist=$(rpm -qf /usr/bin/bogofilter|cut -d- -f4|cut -d. -f3)
		if [ " $dist" = " $bdist" ] ; then
			bversion=$(rpm -qf /usr/bin/bogofilter|cut -d- -f3)
			if [ "$bversion" = "$version" ] ; then
				release=$(rpm -qf /usr/bin/bogofilter | cut -d- -f4 | cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi
echo -n "Build RPM for indimail-spamfilter-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	tmprel=`cat bogofilter-x/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " 1.$release" ] ; then
		echo 1.$release > bogofilter-x/conf-release
		cd bogofilter-x
		make indimail-spamfilter.spec
		cp indimail-spamfilter.spec /tmp
		cd debian
		make
		cd ../..
	else
		cp bogofilter-x/indimail-spamfilter.spec /tmp
	fi
	if [ $verbose -eq 0 ] ; then
		echo "rpmbuild -ba --clean --quiet /tmp/indimail-spamfilter.spec"
		rpmbuild -ba --clean --quiet /tmp/indimail-spamfilter.spec
	else
		echo "rpmbuild -ba --clean /tmp/indimail-spamfilter.spec"
		rpmbuild -ba --clean /tmp/indimail-spamfilter.spec
	fi
	if [ $? -q 0 ] ; then
		/bin/rm -f /tmp/indimail-spamfilter.spec
		build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
		rpm --addsign $rpmbuild/RPMS/$build_arch/indimail-spamfilter-"$version"-"1.$release".$dist.$build_arch.rpm
		rpm --addsign $rpmbuild/SRPMS/indimail-spamfilter-"$version"-"1.$release".$dist.src.rpm
		echo -n "RPM lint for indimail-spamfilter-"$version"-1."$release" (Y/N) - "
		read key
		if [ " $key" = " Y" -o " $key" = " y" ] ; then
			(
			echo indimail-spamfilter
			rpmlint $rpmbuild/RPMS/$build_arch/indimail-spamfilter-"$version"-"1.$release".$dist.$build_arch.rpm
			echo ------------------------
			echo indimail-spamfilter-"$version"-"1.$release".$dist.src.rpm
			rpmlint $rpmbuild/SRPMS/indimail-spamfilter-"$version"-"1.$release".$dist.src.rpm
			echo ------------------------
			) 2>&1 | less
		fi
	else
		/bin/rm -f /tmp/indimail-spamfilter.spec
	fi
fi

if [ $copy_src -eq 1 ] ; then
	echo -n "Remove Source (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		echo "/bin/rm -f $rpmbuild/SOURCES/indimail-spamfilter-$version.tar.bz2"
		/bin/rm -f $rpmbuild/SOURCES/indimail-spamfilter-$version.tar.bz2
		for i in rpmlintrc permissions.easy permissions.secure permissions.paranoid
		do
			echo "/bin/rm -f $rpmbuild/SOURCES/indimail-spamfilter-$i"
			/bin/rm -f $rpmbuild/SOURCES/indimail-spamfilter-$i
		done
	fi
fi
