#!/bin/sh
bogofilter_version=$(cat conf-version)

/bin/rm -rf $HOME/stage
mkdir -p    $HOME/stage
cp -rp . $HOME/stage/indimail-spamfilter-$bogofilter_version
cd $HOME/stage/indimail-spamfilter-$bogofilter_version
make -s debian/Makefile
make -s -C debian
dpkg-buildpackage -tc -b
ls -lt $HOME/stage
