name: bogofilter-wordlist obs trigger

on:
  push:
    branches: [ master ]
    paths:
      - '**/bogofilter-wordlist-x/**'
      - .github/workflows/bogofilter-wordlist-obs.yml
      - '!**/doc/*'
      - '!**.md'
  pull_request:
    branches: [ master ]
    types: [ synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_bogofilter-wordlist
      uses: actions/checkout@v2

    - name: prepare obs
      run: sudo apt-get update; sudo apt-get install curl; cd bogofilter-wordlist-x; ./prepare_obs bogofilter-wordlist
    - uses: actions/upload-artifact@v2
      with:
        name: bogofilter-wordlist
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
    - shell: bash
      name: trigger_obs
      run: |
        mkdir ~/.ssh
        echo "${{secrets.sf_private_key}}" > ~/.private_key
        chmod 600 ~/.private_key
        echo "${{secrets.sf_known_hosts}}" > ~/.ssh/known_hosts
        cd ~
        tar cvfz $GITHUB_WORKSPACE/bogofilter-wordlist-obs.tar.gz *.tar.gz *.spec *.dsc
        # copy to /home/frs/project/indimail
        scp -q -i ~/.private_key $GITHUB_WORKSPACE/bogofilter-wordlist-obs.tar.gz  "${{secrets.sf_user}}:/home/frs/project/indimail/github"
        rm -f ~/.private_key ~/.ssh/known_hosts $GITHUB_WORKSPACE/bogofilter-wordlist-obs.tar.gz
        #curl -H "Authorization: Token ${{secrets.bogofilter_wordlist_obs_token_value}}" -X POST https://build.opensuse.org/trigger/runservice
