name: bogofilter-wordlist FreeBSD CI

on:
  push:
    paths:
      - '**/bogofilter-wordlist-x/**'
      - '**/prepare_obs'
      - '**/catChangeLog'
      - .github/workflows/bogofilter-wordlist-freebsd.yml
      - '!**/bogofilter-wordlist-x/debian/*'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: ubuntu-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: build bogofilter-wordlist
      id: FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN'
        usesh: true
        prepare: pkg install -y automake autoconf libtool pkgconf wget
        run: cd bogofilter-wordlist-x; ./default.configure; make
