name: bogofilter-wordlist obs trigger

on:
  push:
    branches:
      - master
    paths:
      - '**/bogofilter-wordlist-x/**'
      - .github/workflows/bogofilter-wordlist-obs.yml
      - '!**/doc/*'
      - '!**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_bogofilter-wordlist
      uses: actions/checkout@v2

    - name: prepare obs
      run: sudo apt-get update; sudo apt-get install curl; cd bogofilter-wordlist-x; ./prepare_obs bogofilter-wordlist
    - uses: actions/upload-artifact@v2
      with:
        name: bogofilter-wordlist
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
    - shell: bash
      name: trigger_obs
      run: |
        curl -H "Authorization: Token ${{secrets.bogofilter_wordlist_obs_token_value}}" -X POST https://build.opensuse.org/trigger/runservice
