name: bogofilter FreeBSD CI

on:
  push:
    branches:
      - master
    paths:
      - '**/bogofilter-x/**'
      - .github/workflows/bogofilter-freebsd.yml
      - '!**/bogofilter-x/debian/*'
      - '!**/bogofilter-x/doc/*'
      - '!**.md'

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: build bogofilter
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf xmlto db5
        run: cd bogofilter-x; ./default.configure; make
