name: courier-imap FreeBSD CI

on:
  push:
    paths:
      - '**/courier-imap-x/**'
      - .github/workflows/courier-imap-freebsd.yml
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: macos-12
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: build courier-imap
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.3.1
      with:
        envs: 'MYTOKEN'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf pcre pcre2 libidn gdbm
        run: cd courier-imap-x; ./default.configure; make
