name: fetchmail Ubuntu, Mac OSX CI

on:
  push:
    paths:
      - '**/fetchmail-x/**'
      - .github/workflows/fetchmail-c-cpp.yml
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]

    steps:
    - name: extra_packages
      run: |
        if [ "${OS}" = "macos-latest" ] ; then
          brew install automake autoconf libtool pkgconfig openssl
        fi
        if [ "${OS}" = "ubuntu-latest" ] ; then
          sudo apt-get install gcc g++ automake autoconf libtool gettext autopoint
        fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_main
      uses: actions/checkout@v4

    - name: build fetchmail
      run: |
        cd fetchmail-x
        if [ "${OS}" = "macos-latest" ] ; then
          # Dynamically fetch base paths for Homebrew dependencies
          OPENSSL_PREFIX=$(brew --prefix openssl@3)
          export OPENSSL_PREFIX

          # Combine both paths cleanly into your compilation flags
          export CPPFLAGS="-I${OPENSSL_PREFIX}/include"
          export LDFLAGS="-L${OPENSSL_PREFIX}/lib"
        else
          # Standard flags for Ubuntu environment
          export CPPFLAGS=""
          export LDFLAGS=""
        fi
        ./default.configure
        make
      env:
        OS: ${{ matrix.host }}
