name: fetchmail FreeBSD CI

on:
  push:
    pull_request:
      - main
      - master
    branches:
      - master
    paths:
      - '**/fetchmail-x/**'
      - .github/workflows/fetchmail-freebsd.yml
      - '!**.md'
  pull_request:
    branches: [ master ]

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: build fetchmail
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf gettext bison
        run: cd fetchmail-x; ./default.configure; make
