name: fetchmail FreeBSD CI

on:
  push:
    paths:
      - '**/fetchmail-x/**'
      - .github/workflows/fetchmail-freebsd.yml
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: ubuntu-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: build fetchmail
      id: FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf gettext bison
        run: cd fetchmail-x; ./default.configure; make
