name: fetchmail FreeBSD CI

on:
  push:
    paths:
      - '**/fetchmail-x/**'
      - .github/workflows/fetchmail-freebsd.yml
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: macos-10.15
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: build fetchmail
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf gettext bison
        run: cd fetchmail-x; ./default.configure; make
