name: indimail-auth obs trigger

on:
  push:
    branches: [ master ]
    paths:
      - '**/nssd-x/**'
      - '**/pam-multi-x/**'
      - .github/workflows/indimail-auth-obs.yml
      - '!**/doc/*'
      - '!**.md'
  pull_request:
    branches: [ master ]
    types: [ synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_indimail-auth
      uses: actions/checkout@v2
    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: |
        sudo apt-get update; sudo apt-get install curl libssl-dev libpam0g-dev libmysqlclient-dev
        cd libqmail; ./default.configure; make; sudo make install-strip
    - name: prepare obs
      run: |
        cd indimail-auth; ./prepare_obs indimail-auth
    - uses: actions/upload-artifact@v2
      with:
        name: indimail-auth
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
    - shell: bash
      name: trigger_obs
      run: |
        curl -H "Authorization: Token ${{secrets.indimail_auth_obs_token_value}}" -X POST https://build.opensuse.org/trigger/runservice
