name: indimail-access obs trigger

on:
  push:
    branches: [ master ]
    paths:
      - '**/courier-imap-x/**'
      - '**/fetchmail-x/**'
      - '**/indimail-auth/**'
      - .github/workflows/indimail-access-obs.yml
      - '!**/doc/*'
      - '!**.md'
  pull_request:
    branches: [ master ]
    types: [ synchronize ]
    paths:
      - '**/courier-imap-x/**'
      - '**/fetchmail-x/**'
      - '**/indimail-auth/**'
      - .github/workflows/indimail-access-obs.yml
      - '!**/doc/*'
      - '!**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_indimail-access
      uses: actions/checkout@v2

    - name: prepare obs
      run: |
        sudo apt-get update; sudo apt-get install curl automake gettext autopoint libpam0g-dev libpcre3-dev libgdbm-dev libdb-dev libgcrypt20-dev libgamin-dev python libssl-dev bison flex libidn11-dev
        cd indimail-access; ./prepare_obs indimail-access
    - uses: actions/upload-artifact@v2
      with:
        name: indimail-access
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
    - shell: bash
      name: trigger_obs
      run: |
        curl -H "Authorization: Token ${{secrets.indimail_access_obs_token_value}}" -X POST https://build.opensuse.org/trigger/runservice
