name: indimail-access obs trigger

on:
  push:
    branches: [ master ]
    paths:
      - '**/courier-imap-x/**'
      - '**/fetchmail-x/**'
      - '**/indimail-auth/**'
      - .github/workflows/indimail-access-obs.yml
      - '!**/doc/*'
      - '!**.md'
  pull_request:
    branches: [ master ]
    types: [ synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_indimail-access
      uses: actions/checkout@v2

    - name: prepare obs
      run: |
        sudo apt-get update; sudo apt-get install automake gettext autopoint libpam0g-dev libpcre3-dev libgdbm-dev libdb-dev libgcrypt20-dev libgamin-dev python libssl-dev bison flex libidn11-dev
        cd indimail-access; ./prepare_obs indimail-access
    - uses: actions/upload-artifact@v2
      with:
        name: indimail-access
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
    - shell: bash
      name: trigger_obs
      run: |
        mkdir ~/.ssh
        echo "${{secrets.sf_private_key}}" > ~/.private_key
        chmod 600 ~/.private_key
        echo "${{secrets.sf_known_hosts}}" > ~/.ssh/known_hosts
        cd ~
        tar cvfz $GITHUB_WORKSPACE/indimail-access-obs.tar.gz *.tar.gz *.spec *.dsc
        # copy to /home/frs/project/indimail
        scp -q -i ~/.private_key $GITHUB_WORKSPACE/indimail-access-obs.tar.gz  "${{secrets.sf_user}}:${{secrets.sf_path}}"
        rm -f ~/.private_key ~/.ssh/known_hosts $GITHUB_WORKSPACE/indimail-access-obs.tar.gz
