name: indimail-spamfilter FreeBSD CI

on:
  push:
    paths:
      - '**/indimail-spamfilter-x/**'
      - '**/prepare_obs'
      - '**/catChangeLog'
      - .github/workflows/indimail-spamfilter-freebsd.yml
      - '!**/indimail-spamfilter-x/debian/*'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: macos-12
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: build indimail-spamfilter
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.3.1
      with:
        envs: 'MYTOKEN'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf xmlto db5
        run: cd indimail-spamfilter-x; ./default.configure; make
