name: indimail-utils FreeBSD CI

on:
  push:
    paths:
      - '**/altermime-x/**'
      - '**/ripmime-x/**'
      - '**/fortune-x/**'
      - '**/mpack-x/**'
      - '**/flash-x/**'
      - '**/prepare_obs'
      - '**/catChangeLog'
      - .github/workflows/indimail-utils-freebsd.yml
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: ubuntu-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: build indimail-utils
      id: FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf
        run: |
          cd altermime-x; ./default.configure; make; make install
          cd ../ripmime-x; ./default.configure; make; make install
          cd ../fortune-x; ./default.configure; make; make install
          cd ../mpack-x; ./default.configure; make; make install
          cd ../flash-x; ./default.configure; make; make install
