name: indimail-utils Ubuntu, Mac OSX CI

on:
  push:
    branches:
      - master
    paths:
      - '**/indimail-x/altermime-x/**'
      - '**/indimail-x/ripmime-x/**'
      - '**/indimail-x/fortune-x/**'
      - '**/indimail-x/mpack-x/**'
      - '**/indimail-x/flash-x/**'
      - .github/workflows/indimail-utils-c-cpp.yml
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]
    
    steps:
    - name: extra_packages
      run: |
        if [ "${OS}" = "macos-latest" ] ; then brew install automake autoconf libtool pkgconfig ; fi
        if [ "${OS}" = "ubuntu-latest" ] ; then sudo apt-get install gcc g++ automake autoconf libtool libncurses5 libncurses5-dev; fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_main
      uses: actions/checkout@v2
      
    - name: build indimail-utils
      run: |
        cd altermime-x; ./default.configure; make
        cd ../ripmime-x; ./default.configure; make
        cd ../fortune-x; ./default.configure; make
        cd ../mpack-x; ./default.configure; make
        cd ../flash-x; ./default.configure; make
