name: indimail obs trigger

on:
  push:
    branches:
      - master
    paths:
      - '**/indimail-x/**'
      - .github/workflows/indimail-obs.yml
      - '!**/doc/*'
      - '!**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_indimail
      uses: actions/checkout@v2
    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: |
        sudo apt-get update; sudo apt-get install curl libssl-dev libmysqlclient-dev libncurses5-dev
        cd libqmail; ./default.configure; make; sudo make install-strip
    - name: prepare obs
      run: |
        cd indimail-x; ./prepare_obs indimail
    - uses: actions/upload-artifact@v2
      with:
        name: indimail
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
    - shell: bash
      name: trigger_obs
      run: |
        curl -H "Authorization: Token ${{secrets.indimail_obs_token_value}}" -X POST https://build.opensuse.org/trigger/runservice
