name: indimail Ubuntu, Mac OSX CI

on:
  push:
    paths:
      - '**/indimail-x/**'
      - '**/prepare_obs'
      - '**/catChangeLog'
      - .github/workflows/indimail-c-cpp.yml
      - '!**/indimail-x/debian/*'
      - '!**/indimail-x/tests/*'
      - '!**/*.9'
      - '!**/*.8'
      - '!**/*.5'
      - '!**/*.7'
      - '!**/*.3'
      - '!**/*.1'
      - '!**/doc/*'
      - '!**.md'
      - '!**.png'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]

    steps:
    - name: extra_packages
      run: |
        if [ "${OS}" = "macos-latest" ] ; then brew install automake autoconf libtool pkgconfig openssl mysql gsasl; fi
        if [ "${OS}" = "macos-latest" ] ; then sudo mkdir -p /usr/local/include /usr/local/lib; sudo ln -sf /opt/homebrew/Cellar/mysql/9.0.1_4/include/mysql /usr/local/include/mysql; sudo ln -s /opt/homebrew/Cellar/mysql/9.0.1_4/lib/mysql /usr/local/lib/mysql; fi
        if [ "${OS}" = "ubuntu-latest" ] ; then sudo apt-get install gcc g++ automake autoconf libtool libssl-dev libmysqlclient-dev libncurses5-dev libgsasl7-dev; fi
        if [ "${OS}" = "ubuntu-22.04" ] ; then sudo apt-get install gcc g++ automake autoconf libtool libssl-dev libmysqlclient-dev libncurses5-dev libgsasl-dev; fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_main
      uses: actions/checkout@v4
      with:
        path: main

    - name: checkout_qmail
      uses: actions/checkout@v4
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: cd libqmail;env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.2/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.2/lib" ./default.configure; env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.2/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.2/lib" make; sudo make install-strip
    - name: build_indimail-virtualdomains
      run: cd main/indimail-x; env CFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.2/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.2/lib" ./default.configure; env CFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.2/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.2/lib" make
