name: indium FreeBSD CI

on:
  push:
    paths:
      - '**/indium-x/**'
      - '**/prepare_obs'
      - '**/catChangeLog'
      - .github/workflows/indium-freebsd.yml
      - '!**/indium-x/debian/*'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: macos-10.15
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: build indium
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf lang/tcl86 tk86 mysql80-server mysql80-client
        run: cd indium-x; ./default.configure; make
