name: indium Ubuntu CI

on:
  push:
    paths:
      - '**/indium-x/**'
      - '**/prepare_obs'
      - '**/catChangeLog'
      - .github/workflows/indium-c-cpp.yml
      - '!**/indium-x/debian/*'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest]

    steps:
    - name: extra_packages
      run: |
        if [ "${OS}" = "macos-latest" ] ; then brew install automake autoconf libtool pkgconfig tcl-tk mysql; fi
        if [ "${OS}" = "ubuntu-latest" ] ; then sudo apt-get install gcc g++ automake autoconf libtool libmysqlclient-dev tcl-dev; fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_main
      uses: actions/checkout@v2

    - name: build indium
      run: |
        cd indium-x
        ./default.configure; make
      env:
        OS: ${{ matrix.host }}
