name: indimail obs trigger

on:
  push:
    branches:
      - master
    paths:
      - '**/indimail-x/obs_dist/**'
      - .github/workflows/indimail-obs.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: trigger_obs
      shell: bash
      run: |
        curl -H "Authorization: Token ${{secrets.indimail_obs_token_value}}" -X POST https://build.opensuse.org/trigger/runservice
