name: ircube FreeBSD CI

on:
  push:
    paths:
      - '**/ircube-x/**'
      - '**/prepare_obs'
      - '**/catChangeLog'
      - .github/workflows/ircube-freebsd.yml
      - '!**/ircube-x/debian/*'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: macos-12
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: build ircube
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.3.1
      with:
        envs: 'MYTOKEN'
        usesh: true
        prepare: pkg install -y automake autoconf libtool pkgconf
        run: cd ircube-x; ./default.configure; make install
