name: ircube obs trigger

on:
  push:
    paths:
      - '**/ircube-x/**'
      - '**/prepare_obs'
      - '**/catChangeLog'
      - .github/workflows/ircube-obs.yml
      - '!**/doc/*'
      - '!**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_ircube
      uses: actions/checkout@v2

    - name: prepare obs
      run: cd ircube-x; ./prepare_obs ircube
    - uses: actions/upload-artifact@v2
      with:
        name: ircube
        path: ~/stage
    - shell: bash
      name: trigger_obs
      run: |
        mkdir ~/.ssh
        echo "${{secrets.sf_private_key}}" > ~/.private_key
        chmod 600 ~/.private_key
        echo "${{secrets.sf_known_hosts}}" > ~/.ssh/known_hosts
        cd ~/stage
        tar cvfz $GITHUB_WORKSPACE/ircube-obs.tar.gz *
        # copy to /home/frs/project/indimail
        scp -q -i ~/.private_key $GITHUB_WORKSPACE/ircube-obs.tar.gz  "${{secrets.sf_user}}:${{secrets.sf_upload_path}}"
        rm -f ~/.private_key ~/.ssh/known_hosts $GITHUB_WORKSPACE/ircube-obs.tar.gz
        rm -rf ~/stage
