name: ircube Ubuntu, Mac OSX CI

on:
  push:
    paths:
      - '**/ircube-x/**'
      - .github/workflows/ircube-ubuntu-osx.yml
      - '!**/ircube-x/debian/*'
      - '!**/doc/*'
      - '!**.md'

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]

    steps:
    - name: extra_packages
      run: |
        if [ "${OS}" = "macos-latest" ] ; then brew install automake autoconf pkgconfig; fi
        if [ "${OS}" = "ubuntu-latest" ] ; then sudo apt-get install automake autoconf; fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_main
      uses: actions/checkout@v2

    - name: build ircube
      run: cd ircube-x; ./default.configure; sudo make install
