name: ircube FreeBSD CI

on:
  push:
    pull_request:
      - main
      - master
    branches:
      - master
    paths:
      - '**/ircube-x/**'
      - .github/workflows/ircube-freebsd.yml
      - '!**/ircube-x/debian/*'
      - '!**/ircube-x/doc/*'
      - '!**.md'
  pull_request:
    branches: [ master ]

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: build ircube
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y automake autoconf libtool pkgconf
        run: cd ircube-x; ./default.configure; make install
