name: iwebadmin FreeBSD CI

on:
  push:
    branches:
      - master
    paths:
      - '**/iwebadmin-x/**'
      - '**/indimail-x/**'
      - .github/workflows/iwebadmin-freebsd.yml
      - '!**/iwebadmin-x/debian/*'
      - '!**/indimail-x/debian/*'
      - '!**/doc/*'
      - '!**.md'

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail
    - name: build iwebadmin
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf mysql80-server mysql80-client
        run: |
          cd libqmail; ./default.configure; make; make install-strip
          cd ../main/indimail-x; ./default.configure; make install
          cd ../iwebadmin-x; ./default.configure; make
