name: iwebadmin obs trigger

on:
  push:
    branches: [ master ]
    paths:
      - '**/iwebadmin-x/**'
      - .github/workflows/iwebadmin-obs.yml
      - '!**/doc/*'
      - '!**.md'
  pull_request:
    branches: [ master ]
    types: [ synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_iwebadmin
      uses: actions/checkout@v2
    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: |
        sudo apt-get update; sudo apt-get install curl libssl-dev libmysqlclient-dev libncurses5-dev
        cd libqmail; ./default.configure; make; sudo make install-strip
    - name: build_virtualdomains
      run: cd indimail-x; ./default.configure; sudo make install-strip
    - name: prepare obs
      run: cd iwebadmin-x; ./prepare_obs iwebadmin
    - uses: actions/upload-artifact@v2
      with:
        name: iwebadmin
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
    - shell: bash
      name: trigger_obs
      run: |
        curl -H "Authorization: Token ${{secrets.indimail_auth_obs_token_value}}" -X POST https://build.opensuse.org/trigger/runservice
