name: logalert obs trigger

on:
  push:
    branches: [ master ]
    paths:
      - '**/logalert-x/**'
      - .github/workflows/logalert-obs.yml
      - '!**/doc/*'
      - '!**.md'
  pull_request:
    branches: [ master ]
    types: [ synchronize ]
    paths:
      - '**/logalert-x/**'
      - .github/workflows/logalert-obs.yml
      - '!**/doc/*'
      - '!**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_logalert
      uses: actions/checkout@v2
    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail
    - name: install_qmail
      run: |
        sudo apt-get update; sudo apt-get install curl libpcre3-dev flex bison libmysqlclient-dev libncurses5-dev
        cd libqmail; ./default.configure; make; sudo make install-strip
    - name: build_virtualdomains
      run: cd indimail-x; ./default.configure; sudo make install-strip
    - name: prepare obs
      run: cd logalert-x; ./prepare_obs logalert
    - uses: actions/upload-artifact@v2
      with:
        name: logalert
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
    - shell: bash
      name: trigger_obs
      run: |
        curl -H "Authorization: Token ${{secrets.logalert_obs_token_value}}" -X POST https://build.opensuse.org/trigger/runservice
