name: logalert FreeBSD CI

on:
  push:
    paths:
      - '**/logalert-x/**'
      - '**/prepare_obs'
      - '**/catChangeLog'
      - .github/workflows/logalert-freebsd.yml
      - '!**/logalert-x/debian/*'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: macos-12
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail
    - name: build logalert
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.3.0
      with:
        envs: 'MYTOKEN'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf mysql80-server mysql80-client
        run: |
          cd libqmail; ./default.configure; make; make install-strip
          cd ../main/indimail-x; ./default.configure; make install-strip
          cd ../logalert-x; ./default.configure; make
