name: nssd Ubuntu CI

on:
  push:
    branches: [ master ]
    paths:
      - '**/nssd-x/**'
      - .github/workflows/nssd-c-cpp.yml
      - '!**/doc/*'
      - '!**.md'
  pull_request:
    branches: [ master ]
    types: [ synchronize ]

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest]
    
    steps:
    - name: extra_packages
      run: |
        sudo apt-get install gcc g++ automake autoconf libtool libmysqlclient-dev
      env:
        OS: ${{ matrix.host }}

    - name: checkout_main
      uses: actions/checkout@v2
      with:
        path: main
      
    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail
      
    - name: install_qmail
      run: cd libqmail; ./default.configure; make; sudo make install-strip
    - name: build nssd
      run: cd main/nssd-x; ./default.configure; make
