name: nssd FreeBSD CI

on:
  push:
    branches:
      - master
    paths:
      - '**/nssd-x/**'
      - .github/workflows/nssd-freebsd.yml
  pull_request:
    branches: [ master ]

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: build nssd
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf mysql80-server mysql80-client
        run: |
          cd nssd-x; ./default.configure; make
