name: nssd FreeBSD CI

on:
  push:
    paths:
      - '**/nssd-x/**'
      - .github/workflows/nssd-freebsd.yml
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: ubuntu-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: main
    - uses: actions/checkout@v4
      with:
        repository: mbhangui/libqmail
        path: libqmail
    - name: build nssd
      id: FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf mysql80-server mysql80-client
        run: |
          cd libqmail; ./default.configure; make; make install-strip
          cd ../main/nssd-x; ./default.configure; make
