name: pam-multi Ubuntu, Mac OSX CI

on:
  push:
    paths:
      - '**/pam-multi-x/**'
      - .github/workflows/pam-multi-c-cpp.yml
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]

    steps:
    - name: extra_packages
      run: |
        if [ "${OS}" = "macos-latest" ] ; then brew install automake autoconf libtool pkgconfig openssl mysql; fi
        if [ "${OS}" = "macos-latest" ] ; then sudo mkdir -p /usr/local/include /usr/local/lib; sudo ln -sf /opt/homebrew/Cellar/mysql/9.1.0_1/include/mysql /usr/local/include/mysql; sudo ln -s /opt/homebrew/Cellar/mysql/9.1.0_1/lib/mysql /usr/local/lib/mysql; fi
        if [ "${OS}" = "ubuntu-latest" ] ; then sudo apt-get install gcc g++ automake autoconf libtool libpam-modules libpam0g-dev libmysqlclient-dev; fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_main
      uses: actions/checkout@v4
      with:
        path: main

    - name: checkout_qmail
      uses: actions/checkout@v4
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: cd libqmail;env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.4.0/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.4.0/lib" ./default.configure; env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.4.0/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.4.0/lib" make; sudo make install-strip
    - name: build pam-multi
      run: cd main/pam-multi-x; ./default.configure; make
