name: pam-multi FreeBSD CI

on:
  push:
    pull_request:
      - main
      - master
    branches:
      - master
    paths:
      - '**/pam-multi-x/**'
      - .github/workflows/pam-multi-freebsd.yml
      - '!**.md'
  pull_request:
    branches: [ master ]

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail
    - name: build pam-multi
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf mysql80-server mysql80-client
        run: |
          cd libqmail; ./default.configure; make; make install-strip
          cd ../main/pam-multi-x; ./default.configure; make
