name: pam-multi Ubuntu, Mac OSX CI

on:
  push:
    paths:
      - '**/pam-multi-x/**'
      - .github/workflows/pam-multi-c-cpp.yml
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]

    steps:
    - name: extra_packages
      run: |
        if [ "${OS}" = "macos-latest" ] ; then
          brew install automake autoconf libtool pkgconfig openssl mysql
        fi
        if [ "${OS}" = "ubuntu-latest" ] ; then
          sudo apt-get install gcc g++ automake autoconf libtool \
            libpam-modules libpam0g-dev libmysqlclient-dev
        fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_main
      uses: actions/checkout@v4
      with:
        path: main

    - name: checkout_qmail
      uses: actions/checkout@v4
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: |
        if [ "${OS}" = "macos-latest" ] ; then
          # Dynamically fetch base paths for Homebrew dependencies
          OPENSSL_PREFIX=$(brew --prefix openssl@3)

          export CPPFLAGS="-I${OPENSSL_PREFIX}/include"
          export LDFLAGS="-L${OPENSSL_PREFIX}/lib"
        else
          # Standard flags for Ubuntu environment
          export CPPFLAGS=""
          export LDFLAGS=""
        fi
        cd libqmail
        ./default.configure
        make
        sudo make install-strip
      env:
        OS: ${{ matrix.host }}

    - name: build pam-multi
      run: |
        if [ "${OS}" = "macos-latest" ] ; then
          # Dynamically fetch base paths for Homebrew dependencies
          OPENSSL_PREFIX=$(brew --prefix openssl@3)
          MYSQL_PREFIX=$(brew --prefix mysql)
          r=$(realpath ${MYSQL_PREFIX})

          sudo mkdir -p /usr/local/include /usr/local/lib
          sudo ln -sf ${r}/include/mysql /usr/local/include/mysql
          sudo ln -sf ${r}/lib/mysql     /usr/local/lib/mysql
          # Combine both paths cleanly into your compilation flags
          export CPPFLAGS="-I${OPENSSL_PREFIX}/include"
          export LDFLAGS="-L${OPENSSL_PREFIX}/lib"
        else
          # Standard flags for Ubuntu environment
          export CPPFLAGS=""
          export LDFLAGS=""
        fi
        cd main/pam-multi-x
        ./default.configure
        make
      env:
        OS: ${{ matrix.host }}
