name: procmail FreeBSD CI

on:
  push:
    paths:
      - '**/procmail-x/**'
      - '**/prepare_obs'
      - '**/catChangeLog'
      - .github/workflows/procmail-freebsd.yml
      - '!**/procmail-x/debian/*'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: ubuntu-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: build procmail
      id: FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN'
        usesh: true
        prepare: pkg install -y automake autoconf libtool pkgconf
        run: cd procmail-x; ./default.configure; make
