name: procmail FreeBSD CI

on:
  push:
    paths:
      - '**/procmail-x/**'
      - '**/prepare_obs'
      - '**/catChangeLog'
      - .github/workflows/procmail-freebsd.yml
      - '!**/procmail-x/debian/*'
      - '!**/doc/*'
      - '!**.md'

jobs:
  testfreebsd:
    runs-on: macos-10.15
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: build procmail
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y automake autoconf libtool pkgconf
        run: cd procmail-x; ./default.configure; make
