name: procmail obs trigger

on:
  push:
    branches: [ master ]
    paths:
      - '**/procmail-x/**'
      - .github/workflows/procmail-obs.yml
      - '!**/doc/*'
      - '!**.md'
  pull_request:
    branches: [ master ]
    types: [ synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_procmail
      uses: actions/checkout@v2

    - name: prepare obs
      run: cd procmail-x; ./prepare_obs procmail
    - uses: actions/upload-artifact@v2
      with:
        name: procmail
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
    - shell: bash
      name: trigger_obs
      run: |
        mkdir ~/.ssh
        echo "${{secrets.sf_private_key}}" > ~/.private_key
        chmod 600 ~/.private_key
        echo "${{secrets.sf_known_hosts}}" > ~/.ssh/known_hosts
        cd ~
        tar cvfz $GITHUB_WORKSPACE/procmail-obs.tar.gz *.tar.gz *.spec *.dsc
        # copy to /home/frs/project/indimail
        scp -q -i ~/.private_key $GITHUB_WORKSPACE/procmail-obs.tar.gz  "${{secrets.sf_user}}:${{secrets.sf_path}}"
        rm -f ~/.private_key ~/.ssh/known_hosts $GITHUB_WORKSPACE/procmail-obs.tar.gz
